--**********************************************************************************************************************
-- MEMBER ���̺� ����
DROP TABLE MEMBER CASCADE CONSTRAINTS;
-- MEMBER ���̺� ����
CREATE TABLE MEMBER (
    MNUM NUMBER,
    MEMBER_ID VARCHAR2(20) CONSTRAINT PKID PRIMARY KEY NOT NULL,
    MEMBER_PWD VARCHAR2(20) CONSTRAINT MPWD NOT NULL,
    MEMBER_NAME VARCHAR2(20) CONSTRAINT MNAME NOT NULL,
    MEMBER_EMAIL VARCHAR2(20) CONSTRAINT MEMAIL NOT NULL,
    EMAILAUTH VARCHAR2(20) CONSTRAINT MAUTH NOT NULL,
    MEMBER_PHONE VARCHAR2(15) CONSTRAINT MPHONE NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE,
    LAST_ACCESS_DATE DATE DEFAULT SYSDATE,
   SECESSION_OK CHAR(1)   DEFAULT 'Y'   CONSTRAINT SS_OK NOT NULL,
    CONSTRAINT CHK_SES CHECK (SECESSION_OK IN ('Y','N')),
    SECESSION_DATE DATE DEFAULT SYSDATE
);

-- MEMBER �÷���
COMMENT ON COLUMN MEMBER.MNUM IS '��ȣ';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS 'ȸ�� ���̵�';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS 'ȸ�� �н�����';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS 'ȸ�� �̸�';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS 'ȸ�� �̸���';
COMMENT ON COLUMN MEMBER.EMAILAUTH IS '�̸�������';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS 'ȸ�� ��ȭ��ȣ';
COMMENT ON COLUMN MEMBER.JOIN_DATE IS '������';
COMMENT ON COLUMN MEMBER.LAST_ACCESS_DATE IS '�ֱ�������';
COMMENT ON COLUMN MEMBER.SECESSION_OK IS 'Ż�𿩺�';
COMMENT ON COLUMN MEMBER.SECESSION_DATE IS 'Ż����';

INSERT INTO MEMBER VALUES('1', 'admin', 'YWRtaW4=', '���¿�', 'spark1048@naver.com', 'SHA1', '010-3387-7583', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('2', 'user01', 'dXNlcjAx', '�̼���', 'user01@naver.com', 'SHA2', '010-1111-1111', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('3', 'user02', 'YWRtaW4=', '���¿�', 'spark1048@naver.com', 'SHA1', '010-3387-7583', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('4', 'user03', 'dXNlcjAx', '�̼���', 'user01@naver.com', 'SHA2', '010-1111-1111', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('5', 'user04', 'YWRtaW4=', '���¿�', 'spark1048@naver.com', 'SHA1', '010-3387-7583', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('6', 'user05', 'dXNlcjAx', '�̼���', 'user01@naver.com', 'SHA2', '010-1111-1111', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('7', 'user06', 'YWRtaW4=', '���¿�', 'spark1048@naver.com', 'SHA1', '010-3387-7583', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('8', 'user07', 'dXNlcjAx', '�̼���', 'user01@naver.com', 'SHA2', '010-1111-1111', DEFAULT, DEFAULT, 'N', DEFAULT);
INSERT INTO MEMBER VALUES('9', 'user08', 'dXNlcjAy', '����', 'user02@naver.com', 'SHA3', '010-2222-2222', DEFAULT, DEFAULT, 'Y', DEFAULT);
INSERT INTO MEMBER VALUES('10', 'user09', 'dXNlcjAz', '��ù�', 'user03@naver.com', 'SHA4', '010-3333-3333', DEFAULT, DEFAULT, 'Y', DEFAULT);
INSERT INTO MEMBER VALUES('11', 'user10', 'dXNlcjAz', '��ù�', 'user03@naver.com', 'SHA4', '010-3333-3333', DEFAULT, DEFAULT, 'Y', DEFAULT);
INSERT INTO MEMBER VALUES('12', 'user11', 'dXNlcjAz', '��ù�', 'user03@naver.com', 'SHA4', '010-3333-3333', DEFAULT, DEFAULT, 'Y', DEFAULT);

--**********************************************************************************************************************


-- ���̺� ����
DROP TABLE BANNER  CASCADE CONSTRAINTS;
-- ��� ���� ���̺� ����
CREATE TABLE BANNER (
   BANNER_NO    NUMBER CONSTRAINT PK_BA PRIMARY KEY,
   BANNER_TITLE   VARCHAR2(50),    
   BANNER_CHK   CHAR(1)   DEFAULT 'H',
   BANNER_CONTENT    VARCHAR2(4000),   
   BANNER_ORIGINAL   VARCHAR2(50),
   BANNER_RENAME   VARCHAR2(50),
   BANNER_SIZE   VARCHAR2(20),
    BANNER_URL   VARCHAR2(50),
    CONSTRAINT CHK_BAC CHECK (BANNER_CHK IN ('H','W'))
);

COMMENT ON COLUMN "BANNER"."BANNER_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "BANNER"."BANNER_TITLE" IS '�������';
COMMENT ON COLUMN "BANNER"."BANNER_CHK" IS '�Խù�ʰ���';
COMMENT ON COLUMN "BANNER"."BANNER_CONTENT" IS '����';
COMMENT ON COLUMN "BANNER"."BANNER_ORIGINAL" IS '�������ϸ�';
COMMENT ON COLUMN "BANNER"."BANNER_RENAME" IS '�ٲ����ϸ�';
COMMENT ON COLUMN "BANNER"."BANNER_SIZE" IS '������';
COMMENT ON COLUMN "BANNER"."BANNER_URL" IS 'URL';


-- ���̺� ����
DROP TABLE DECLARE_ADMIN CASCADE CONSTRAINTS;
-- �Ű��� ���� ���̺� ����
CREATE TABLE DECLARE_ADMIN (
   DECLARE_NO NUMBER    CONSTRAINT PK_DNO PRIMARY KEY,
   DECLARE_ID   VARCHAR2(20)      CONSTRAINT NN_ID NOT NULL,
   DECLARE_COUNT   NUMBER      CONSTRAINT NN_COUNT  NOT NULL,
   DECLARE_OK CHAR(1)   DEFAULT 'Y'   CONSTRAINT NN_OK NOT NULL,
    CONSTRAINT CHK_DOK CHECK (DECLARE_OK IN ('Y','N'))
);

COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_NO" IS '����';
COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_ID" IS '�Ű�ȸ��';
COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_COUNT" IS '�Ű����� Ƚ��';
COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_OK" IS '���Ѽ���';

ALTER TABLE DECLARE_ADMIN ADD CONSTRAINT FK_DECLARE_ID FOREIGN KEY(DECLARE_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE;

INSERT INTO DECLARE_ADMIN VALUES(1, 'user08', 2, DEFAULT);
INSERT INTO DECLARE_ADMIN VALUES(2, 'user01', 1, DEFAULT);
INSERT INTO DECLARE_ADMIN VALUES(3, 'user03', 4, DEFAULT);

COMMIT;

-- ���� ������ ��� ���̵� ��ȸ�� ����� ������
SELECT MEMBER_ID, DECLARE_OK FROM MEMBER 
LEFT JOIN DECLARE_ADMIN ON(MEMBER_ID = DECLARE_ID)
where declare_ok='Y';

INSERT INTO BANNER
VALUES(1, '����', DEFAULT, '���ι��', 'MAIIN.jpg', '', '1080x350', 'url' );
INSERT INTO BANNER
VALUES(2, 'sky', DEFAULT, '�ϴù��', 'sky.jpg', '', '1080x350', 'url' );
INSERT INTO BANNER
VALUES(3, 'bless', DEFAULT, '�̿����', 'visual.jpg', '', '1920x740', 'url' );

COMMIT;


-- ������ �ִ� �������� DB����
DROP TABLE FBOARD_COMMENT CASCADE CONSTRAINTS;    --���̺� ����
DROP TABLE FESTIVAL_INFORMATION CASCADE CONSTRAINTS;    -- ���� ����

-- ���� �з�
DROP TABLE LOCATION CASCADE CONSTRAINTS;    --���̺� ����

CREATE TABLE LOCATION (
   local_no   VARCHAR2(3)      NOT NULL,   -- PK
   local_name   VARCHAR2(20)      NOT NULL,
   kmap_y   VARCHAR2(30)      NULL,
    kmap_x   VARCHAR2(30)      NULL,
    CONSTRAINT PK_local_no PRIMARY KEY (local_no)
);

COMMENT ON COLUMN LOCATION.local_no IS '������ȣ';
COMMENT ON COLUMN LOCATION.local_name IS '�����̸�(��)';
COMMENT ON COLUMN LOCATION.kmap_y IS '������ �߽� ��ġ ����';
COMMENT ON COLUMN LOCATION.kmap_x IS '������ �߽� ��ġ �浵';

-- ���� ������ ����
INSERT INTO LOCATION(local_no, local_name, kmap_y, kmap_x)
SELECT '1', '������', '37.4959854', '127.0664091' FROM DUAL UNION ALL
SELECT '2', '������', '37.5492077', '127.1464824' FROM DUAL UNION ALL
SELECT '3', '���ϱ�', '37.6469954', '127.0147158' FROM DUAL UNION ALL
SELECT '4', '������', '37.5657617', '126.8226561' FROM DUAL UNION ALL
SELECT '5', '���Ǳ�', '37.4653993', '126.9438071' FROM DUAL UNION ALL
SELECT '6', '������', '37.5481445', '127.0857528' FROM DUAL UNION ALL
SELECT '7', '���α�', '37.4954856', '126.858121' FROM DUAL UNION ALL
SELECT '8', '��õ��', '37.4600969', '126.9001546' FROM DUAL UNION ALL
SELECT '9', '�����', '37.655264', '127.0771201' FROM DUAL UNION ALL
SELECT '10', '������', '37.6658609', '127.0317674' FROM DUAL UNION ALL
SELECT '11', '���빮��', '37.5838012', '127.0507003' FROM DUAL UNION ALL
SELECT '12', '���۱�', '37.4965037', '126.9443073' FROM DUAL UNION ALL
SELECT '13', '������', '37.5622906', '126.9087803' FROM DUAL UNION ALL
SELECT '14', '���빮��', '37.5820369', '126.9356665' FROM DUAL UNION ALL
SELECT '15', '���ʱ�', '37.4769528', '127.0378103' FROM DUAL UNION ALL
SELECT '16', '������', '37.5506753', '127.0409622' FROM DUAL UNION ALL
SELECT '17', '���ϱ�' ,'37.606991', '127.0232185' FROM DUAL UNION ALL
SELECT '18', '���ı�' ,'37.5048534', '127.1144822' FROM DUAL UNION ALL
SELECT '19', '��õ��', '37.5270616', '126.8561534' FROM DUAL UNION ALL
SELECT '20', '��������', '37.520641', '126.9139242' FROM DUAL UNION ALL
SELECT '21', '��걸', '37.5311008', '126.9810742' FROM DUAL UNION ALL
SELECT '22', '����', '37.6176125', '126.9227004' FROM DUAL UNION ALL
SELECT '23', '���α�', '37.5990998', '126.9861493' FROM DUAL UNION ALL
SELECT '24', '�߱�', '37.5579452', '126.9941904' FROM DUAL UNION ALL
SELECT '25', '�߶���', '37.5953795', '127.0939669' FROM DUAL;

COMMIT;


<<<<<<< HEAD
-- ���� �Խ���
DROP TABLE FBOARD CASCADE CONSTRAINTS;    -- ���̺� ����

CREATE TABLE FBOARD (
<<<<<<< HEAD
=======
-- ���� �Խ���
DROP TABLE FBOARD CASCADE CONSTRAINTS;    -- ���̺� ����

CREATE TABLE FBOARD (
>>>>>>> origin/faq4
   fboard_no   VARCHAR2(30)      NOT NULL,   -- PK
    festival_title   VARCHAR2(600)      NOT NULL,
    local_no   VARCHAR2(3)      NOT NULL,
    festival_startdate   VARCHAR2(8),
   festival_enddate   VARCHAR2(8),
    festival_modifieddate   VARCHAR2(20),
    map_y   VARCHAR2(30),
   map_x   VARCHAR2(30),
   bmodify_date   DATE   DEFAULT SYSDATE   ,
    MEMBER_ID   VARCHAR2(20)   ,    -- FK : MEMBER(MEMBER_ID)
   readcount   NUMBER   DEFAULT 0    NULL,
   THUMBNAIL VARCHAR2(100 BYTE) DEFAULT 'NoImage', 
<<<<<<< HEAD
=======
	fboard_no	VARCHAR2(30)		NOT NULL,   -- PK
    festival_title	VARCHAR2(600)		NOT NULL,
    local_no	VARCHAR2(3)		NOT NULL,
    festival_startdate	VARCHAR2(8),
	festival_enddate	VARCHAR2(8),
    festival_modifieddate	VARCHAR2(20),
    map_y	VARCHAR2(30),
	map_x	VARCHAR2(30),
	bmodify_date	DATE	DEFAULT SYSDATE	,
    MEMBER_ID	VARCHAR2(20)	,    -- FK : MEMBER(MEMBER_ID)
	readcount	NUMBER	DEFAULT 0 	NULL,
	THUMBNAIL VARCHAR2(100 BYTE) DEFAULT 'NoImage', 
>>>>>>> origin/member_home
    CONSTRAINT PK_fboard_no PRIMARY KEY (fboard_no)
);

COMMENT ON COLUMN FBOARD.fboard_no IS '�����Խ��� ��ȣ';
COMMENT ON COLUMN FBOARD.festival_title IS '���� �̸�';
COMMENT ON COLUMN FBOARD.local_no IS '���� ��ȣ';
COMMENT ON COLUMN FBOARD.festival_startdate IS '���� ������';
COMMENT ON COLUMN FBOARD.festival_enddate IS '���� ������';
COMMENT ON COLUMN FBOARD.festival_modifieddate IS '���� ������';
COMMENT ON COLUMN FBOARD.map_y IS '���� ����';
COMMENT ON COLUMN FBOARD.map_x IS '���� �浵';
COMMENT ON COLUMN FBOARD.bmodify_date IS '�����Խ��� ������';
COMMENT ON COLUMN FBOARD.MEMBER_ID IS '�ۼ���';
COMMENT ON COLUMN FBOARD.readcount IS '��ȸ��';
COMMENT ON COLUMN FBOARD.Thumbnail IS '�����';


-- ���� �Խ��� ���
DROP TABLE FBOARD_REPLY CASCADE CONSTRAINTS;    -- ���̺� ����

CREATE TABLE FBOARD_REPLY (
<<<<<<< HEAD
   fboardReply_no    NUMBER   NOT NULL,   -- PK
   fboard_no   VARCHAR2(30)      NOT NULL,   -- FK : FBOARD(fboard_no), �Խù� ��ȣ
   MEMBER_ID   VARCHAR2(20),   --�ۼ��� ���̵�
    fboardReply_content VARCHAR2(4000) NOT NULL, --��� ����
    fboardReply_lev NUMBER NOT NULL,    -- ��� (1), ���� (2)
    fboardReply_ref NUMBER,    -- ���� ��� ��ȣ ����� 1�϶��� �ڱ��ȣ
    fboardReply_creatdate   VARCHAR2(40)    NOT NULL,   --��� �ۼ���¥
=======
	fboardReply_no 	NUMBER	NOT NULL,   -- PK
	fboard_no	VARCHAR2(30)		NOT NULL,   -- FK : FBOARD(fboard_no), �Խù� ��ȣ
	MEMBER_ID	VARCHAR2(20),   --�ۼ��� ���̵�
    fboardReply_content VARCHAR2(4000) NOT NULL, --��� ����
    fboardReply_lev NUMBER NOT NULL,    -- ��� (1), ���� (2)
    fboardReply_ref NUMBER,    -- ���� ��� ��ȣ ����� 1�϶��� �ڱ��ȣ
    fboardReply_creatdate	VARCHAR2(40) 	NOT NULL,   --��� �ۼ���¥
>>>>>>> origin/member_home
    CONSTRAINT PK_fboardReply_no PRIMARY KEY (fboardReply_no)
);

COMMENT ON COLUMN FBOARD_REPLY.fboardReply_no IS '��� ��ȣ';
COMMENT ON COLUMN FBOARD_REPLY.fboard_no IS '�Խ��� ��ȣ';
COMMENT ON COLUMN FBOARD_REPLY.MEMBER_ID IS '�ۼ��� id';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_content IS '��� ����';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_lev IS '�۷���';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_ref IS '�θ� ��۹�ȣ';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_creatdate IS '��� �ۼ���¥';
<<<<<<< HEAD
=======

-- fboardReply_no ���� ������ ����
CREATE SEQUENCE FBREPLY_SEQ INCREMENT BY 1 START WITH 1;

-- FK����
ALTER TABLE FBOARD ADD CONSTRAINT FK_local_no FOREIGN KEY(local_no) REFERENCES LOCATION(local_no);    -- LOCATION(local_no);
ALTER TABLE FBOARD ADD CONSTRAINT FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID); -- MEMBER(MEMBER_ID); 
ALTER TABLE FBOARD_REPLY ADD CONSTRAINT FK_fboard_no FOREIGN KEY(fboard_no) REFERENCES FBOARD(fboard_no) ON DELETE CASCADE;   -- FBOARD(fboard_no),  ���� �Խ��� ���� �� ��۵� ����

--oracle sessions �� �ø���
--show parameter processes;
--alter system set processes=300 scope=spfile;
>>>>>>> origin/member_home

-- fboardReply_no ���� ������ ����
CREATE SEQUENCE FBREPLY_SEQ INCREMENT BY 1 START WITH 1;

-- FK����
ALTER TABLE FBOARD ADD CONSTRAINT FK_local_no FOREIGN KEY(local_no) REFERENCES LOCATION(local_no);    -- LOCATION(local_no);
ALTER TABLE FBOARD ADD CONSTRAINT FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID); -- MEMBER(MEMBER_ID); 
ALTER TABLE FBOARD_REPLY ADD CONSTRAINT FK_fboard_no FOREIGN KEY(fboard_no) REFERENCES FBOARD(fboard_no) ON DELETE CASCADE;   -- FBOARD(fboard_no),  ���� �Խ��� ���� �� ��۵� ����

--oracle sessions �� �ø���
=======
    CONSTRAINT PK_fboard_no PRIMARY KEY (fboard_no)
);

COMMENT ON COLUMN FBOARD.fboard_no IS '�����Խ��� ��ȣ';
COMMENT ON COLUMN FBOARD.festival_title IS '���� �̸�';
COMMENT ON COLUMN FBOARD.local_no IS '���� ��ȣ';
COMMENT ON COLUMN FBOARD.festival_startdate IS '���� ������';
COMMENT ON COLUMN FBOARD.festival_enddate IS '���� ������';
COMMENT ON COLUMN FBOARD.festival_modifieddate IS '���� ������';
COMMENT ON COLUMN FBOARD.map_y IS '���� ����';
COMMENT ON COLUMN FBOARD.map_x IS '���� �浵';
COMMENT ON COLUMN FBOARD.bmodify_date IS '�����Խ��� ������';
COMMENT ON COLUMN FBOARD.MEMBER_ID IS '�ۼ���';
COMMENT ON COLUMN FBOARD.readcount IS '��ȸ��';
COMMENT ON COLUMN FBOARD.Thumbnail IS '�����';


-- ���� �Խ��� ���
DROP TABLE FBOARD_REPLY CASCADE CONSTRAINTS;    -- ���̺� ����

CREATE TABLE FBOARD_REPLY (
   fboardReply_no    NUMBER   NOT NULL,   -- PK
   fboard_no   VARCHAR2(30)      NOT NULL,   -- FK : FBOARD(fboard_no), �Խù� ��ȣ
   MEMBER_ID   VARCHAR2(20),   --�ۼ��� ���̵�
    fboardReply_content VARCHAR2(4000) NOT NULL, --��� ����
    fboardReply_lev NUMBER NOT NULL,    -- ��� (1), ���� (2)
    fboardReply_ref NUMBER,    -- ���� ��� ��ȣ ����� 1�϶��� �ڱ��ȣ
    fboardReply_creatdate   VARCHAR2(40)    NOT NULL,   --��� �ۼ���¥
    CONSTRAINT PK_fboardReply_no PRIMARY KEY (fboardReply_no)
);

COMMENT ON COLUMN FBOARD_REPLY.fboardReply_no IS '��� ��ȣ';
COMMENT ON COLUMN FBOARD_REPLY.fboard_no IS '�Խ��� ��ȣ';
COMMENT ON COLUMN FBOARD_REPLY.MEMBER_ID IS '�ۼ��� id';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_content IS '��� ����';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_lev IS '�۷���';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_ref IS '�θ� ��۹�ȣ';
COMMENT ON COLUMN FBOARD_REPLY.fboardReply_creatdate IS '��� �ۼ���¥';

-- fboardReply_no ���� ������ ����
CREATE SEQUENCE FBREPLY_SEQ INCREMENT BY 1 START WITH 1;

-- FK����
ALTER TABLE FBOARD ADD CONSTRAINT FK_local_no FOREIGN KEY(local_no) REFERENCES LOCATION(local_no);    -- LOCATION(local_no);
ALTER TABLE FBOARD ADD CONSTRAINT FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID); -- MEMBER(MEMBER_ID); 
ALTER TABLE FBOARD_REPLY ADD CONSTRAINT FK_fboard_no FOREIGN KEY(fboard_no) REFERENCES FBOARD(fboard_no) ON DELETE CASCADE;   -- FBOARD(fboard_no),  ���� �Խ��� ���� �� ��۵� ����

--oracle sessions �� �ø���
>>>>>>> origin/faq4
--show parameter processes;
--alter system set processes=300 scope=spfile;

----**********************************************************************************************************************

--Ŀ�´�Ƽ
DROP SEQUENCE CBOARD_SEQ;
DROP SEQUENCE CREPLY_SEQ;
DROP TABLE CBOARD CASCADE CONSTRAINTS;
DROP TABLE CREPLY CASCADE CONSTRAINTS;

CREATE SEQUENCE CBOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE CREPLY_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE CBOARD (
	"CBOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CBOARD_TITLE"	VARCHAR2(50)		NOT NULL,
	"CBOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CBOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CBOARD_LASTMODIFIED"	DATE	DEFAULT SYSDATE	NULL,
	"CBOARD_VIEWCOUNT"	NUMBER	DEFAULT 0	NULL,
	"CBOARD_REPLYCOUNT"	NUMBER	DEFAULT 0	NULL,
	"CBOARD_LIKECOUNT"	NUMBER	DEFAULT 0	NULL,
	"LOCAL_NO"	VARCHAR2(3)		NOT NULL,
	"CFILES_ORIGINAL_FILEPATH1"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH1"	VARCHAR2(50)		NULL,
	"CFILES_ORIGINAL_FILEPATH2"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH2"	VARCHAR2(50)		NULL,
	"CFILES_ORIGINAL_FILEPATH3"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH3"	VARCHAR2(50)		NULL,
	"CFILES_ORIGINAL_FILEPATH4"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH4"	VARCHAR2(50)		NULL
);

<<<<<<< HEAD
COMMENT ON COLUMN "CBOARD"."CBOARD_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "CBOARD"."MEMBER_ID" IS 'ȸ�� ���̵�';
COMMENT ON COLUMN "CBOARD"."CBOARD_TITLE" IS '������';
COMMENT ON COLUMN "CBOARD"."CBOARD_CONTENT" IS '�۳���';
COMMENT ON COLUMN "CBOARD"."CBOARD_DATE" IS '�ۼ���';
COMMENT ON COLUMN "CBOARD"."CBOARD_LASTMODIFIED" IS '������������';
COMMENT ON COLUMN "CBOARD"."CBOARD_VIEWCOUNT" IS '��ȸ��';
COMMENT ON COLUMN "CBOARD"."CBOARD_REPLYCOUNT" IS '��ۼ�';
COMMENT ON COLUMN "CBOARD"."CBOARD_LIKECOUNT" IS '���ƿ��';
<<<<<<< HEAD
=======
COMMENT ON COLUMN "CBOARD"."CBOARD_REPORTCOUNT" IS '�Ű���';
COMMENT ON COLUMN "CBOARD"."CBOARD_DISPLAY" IS '��ǥ�ÿ���';
>>>>>>> origin/member_home
COMMENT ON COLUMN "CBOARD"."LOCAL_NO" IS '������ȣ';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH1" IS '�������ϸ�1';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH1" IS '�������ϸ�1';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH2" IS '�������ϸ�2';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH2" IS '�������ϸ�2';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH3" IS '�������ϸ�3';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH3" IS '�������ϸ�3';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH4" IS '�������ϸ�4';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH4" IS '�������ϸ�4';
=======
COMMENT ON COLUMN "CBOARD"."CBOARD_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "CBOARD"."MEMBER_ID" IS 'ȸ�� ���̵�';
COMMENT ON COLUMN "CBOARD"."CBOARD_TITLE" IS '������';
COMMENT ON COLUMN "CBOARD"."CBOARD_CONTENT" IS '�۳���';
COMMENT ON COLUMN "CBOARD"."CBOARD_DATE" IS '�ۼ���';
COMMENT ON COLUMN "CBOARD"."CBOARD_LASTMODIFIED" IS '������������';
COMMENT ON COLUMN "CBOARD"."CBOARD_VIEWCOUNT" IS '��ȸ��';
COMMENT ON COLUMN "CBOARD"."CBOARD_REPLYCOUNT" IS '��ۼ�';
COMMENT ON COLUMN "CBOARD"."CBOARD_LIKECOUNT" IS '���ƿ��';
COMMENT ON COLUMN "CBOARD"."LOCAL_NO" IS '������ȣ';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH1" IS '�������ϸ�1';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH1" IS '�������ϸ�1';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH2" IS '�������ϸ�2';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH2" IS '�������ϸ�2';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH3" IS '�������ϸ�3';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH3" IS '�������ϸ�3';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH4" IS '�������ϸ�4';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH4" IS '�������ϸ�4';
>>>>>>> origin/faq4

CREATE TABLE CREPLY (
	"CREPLY_NO"	NUMBER		NOT NULL,
	"CBOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CREPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CREPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"PARANT_REPLY"	NUMBER		NULL,
	"CREPLY_DEPTH"	NUMBER	DEFAULT 1	NOT NULL
);

<<<<<<< HEAD
COMMENT ON COLUMN "CREPLY"."CREPLY_NO" IS '��۹�ȣ';
COMMENT ON COLUMN "CREPLY"."CBOARD_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "CREPLY"."MEMBER_ID" IS 'ȸ�� ���̵�';
COMMENT ON COLUMN "CREPLY"."CREPLY_DATE" IS '�ۼ���';
COMMENT ON COLUMN "CREPLY"."CREPLY_CONTENT" IS '��۳���';
COMMENT ON COLUMN "CREPLY"."PARANT_REPLY" IS '�θ��۹�ȣ';
<<<<<<< HEAD
=======
COMMENT ON COLUMN "CREPLY"."CREPLY_ORDER" IS '��ۼ���';
>>>>>>> origin/member_home
COMMENT ON COLUMN "CREPLY"."CREPLY_DEPTH" IS '��۱���';
=======
COMMENT ON COLUMN "CREPLY"."CREPLY_NO" IS '��۹�ȣ';
COMMENT ON COLUMN "CREPLY"."CBOARD_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "CREPLY"."MEMBER_ID" IS 'ȸ�� ���̵�';
COMMENT ON COLUMN "CREPLY"."CREPLY_DATE" IS '�ۼ���';
COMMENT ON COLUMN "CREPLY"."CREPLY_CONTENT" IS '��۳���';
COMMENT ON COLUMN "CREPLY"."PARANT_REPLY" IS '�θ��۹�ȣ';
COMMENT ON COLUMN "CREPLY"."CREPLY_DEPTH" IS '��۱���';
>>>>>>> origin/faq4

ALTER TABLE CBOARD ADD CONSTRAINT PK_CBOARD PRIMARY KEY (CBOARD_NO);
ALTER TABLE CREPLY ADD CONSTRAINT PK_CREPLY PRIMARY KEY (CREPLY_NO);
ALTER TABLE CBOARD ADD CONSTRAINT CHK_COBARD_DISPLAY CHECK (CBOARD_DISPLAY IN ('Y', 'N'));
ALTER TABLE CREPLY ADD CONSTRAINT CHK_CREPLY_DEPTH CHECK (CREPLY_DEPTH IN (1, 2));
ALTER TABLE "CBOARD" ADD CONSTRAINT "FK_MEMBER_TO_CBOARD" FOREIGN KEY(MEMBER_ID)REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE;
ALTER TABLE "CBOARD" ADD CONSTRAINT "FK_LOCATION_TO_CBOARD" FOREIGN KEY (LOCAL_NO)REFERENCES LOCATION (LOCAL_NO)ON DELETE CASCADE;
ALTER TABLE "CREPLY" ADD CONSTRAINT "FK_CBOARD_TO_CREPLY" FOREIGN KEY (CBOARD_NO)REFERENCES CBOARD (CBOARD_NO)ON DELETE CASCADE;
ALTER TABLE "CREPLY" ADD CONSTRAINT "FK_MEMBER_TO_CREPLY" FOREIGN KEY (MEMBER_ID)REFERENCES MEMBER (MEMBER_ID)ON DELETE CASCADE;

commit;

-- sample data
INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', 'ù��° �Խñ�', 'ù��° ����', DEFAULT, 1);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�ι�° �Խñ�', '�ι�° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '����° �Խñ�', '����° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�׹�° �Խñ�', '�׹�° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�ټ���° �Խñ�', '�ټ���° ����', DEFAULT, 5);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
<<<<<<< HEAD
<<<<<<< HEAD
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', 'ù��° �Խñ�', '������° ����', DEFAULT, 1);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�ι�° �Խñ�', '�ϰ���° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '����° �Խñ�', '������° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '�׹�° �Խñ�', '��ȩ��° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�ټ���° �Խñ�', '����° ����', DEFAULT, 5);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', 'ù��° �Խñ�', 'ù��° ����', DEFAULT, 1);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '�ι�° �Խñ�', '�ι�° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '����° �Խñ�', '����° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�׹�° �Խñ�', '�׹�° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '�ټ���° �Խñ�', '�ټ���° ����', DEFAULT, 5);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', 'ù��° �Խñ�', '������° ����', DEFAULT, 1);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�ι�° �Խñ�', '�ϰ���° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '����° �Խñ�', '������° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�׹�° �Խñ�', '��ȩ��° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '����° �Խñ�', '����° ����', DEFAULT, 5);
-- sample data
INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 1, 'user01', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 2, 'user02', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 3, 'user03', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 4, 'user01', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 5, 'user02', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 6, 'user03', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 7, 'user01', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 8, 'user02', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 9, 'user03', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 10, 'user01', DEFAULT, 'ù��° ����', DEFAULT);
=======
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '������° �Խñ�', '������° ����', DEFAULT, 6);
=======
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', 'ù��° �Խñ�', '������° ����', DEFAULT, 1);
>>>>>>> origin/faq4

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�ι�° �Խñ�', '�ϰ���° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '����° �Խñ�', '������° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '�׹�° �Խñ�', '��ȩ��° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�ټ���° �Խñ�', '����° ����', DEFAULT, 5);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', 'ù��° �Խñ�', 'ù��° ����', DEFAULT, 1);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '�ι�° �Խñ�', '�ι�° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '����° �Խñ�', '����° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�׹�° �Խñ�', '�׹�° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '�ټ���° �Խñ�', '�ټ���° ����', DEFAULT, 5);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', 'ù��° �Խñ�', '������° ����', DEFAULT, 1);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�ι�° �Խñ�', '�ϰ���° ����', DEFAULT, 2);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user03', '����° �Խñ�', '������° ����', DEFAULT, 3);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�׹�° �Խñ�', '��ȩ��° ����', DEFAULT, 4);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE, LOCAL_NO) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '����° �Խñ�', '����° ����', DEFAULT, 5);
-- sample data
INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 1, 'user01', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 2, 'user02', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 3, 'user03', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 4, 'user01', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 5, 'user02', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 6, 'user03', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 7, 'user01', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 8, 'user02', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
VALUES(CREPLY_SEQ.NEXTVAL, 9, 'user03', DEFAULT, 'ù��° ����', DEFAULT);

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT, CREPLY_DEPTH) 
<<<<<<< HEAD
VALUES(CREPLY_SEQ.NEXTVAL, 5, 'user02', DEFAULT, '�ټ���° ����', DEFAULT);
>>>>>>> origin/member_home
=======
VALUES(CREPLY_SEQ.NEXTVAL, 10, 'user01', DEFAULT, 'ù��° ����', DEFAULT);
>>>>>>> origin/faq4

commit;

--**********************************************************************************************************************

<<<<<<< HEAD
--�߰��ŷ���Ʈ
<<<<<<< HEAD
=======
DROP TABLE JBOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE JBOARD CASCADE CONSTRAINTS;
>>>>>>> origin/member_home
=======
--�߰��ŷ���Ʈ
>>>>>>> origin/faq4

DROP TABLE JBOARD CASCADE CONSTRAINTS;
DROP TABLE JBOARD_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE JBOARD (
   JBOARD_NO   NUMBER      NOT NULL,
   JBOARD_TITLE   VARCHAR2(50)      NOT NULL,
   JBOARD_CONTENT   VARCHAR2(4000)      NOT NULL,
   JBOARD_PRICE   NUMBER      NOT NULL,
   JBOARD_DATE   DATE   DEFAULT SYSDATE   NOT NULL,
   JBOARD_UPDATE   DATE   DEFAULT SYSDATE   NULL,
   JBOARD_COUNT   NUMBER   DEFAULT 0   NULL,
   JBOARD_LIKE   NUMBER   DEFAULT 0   NULL,
   JFILES_ORIGINAL_FILEPATH1   VARCHAR2(50)      NULL,
   JFILES_RENAME_FILEPATH1   VARCHAR2(50)      NULL,
   JFILES_ORIGINAL_FILEPATH2   VARCHAR2(50)      NULL,
   JFILES_RENAME_FILEPATH2   VARCHAR2(50)      NULL,
   JFILES_ORIGINAL_FILEPATH3   VARCHAR2(50)      NULL,
   JFILES_RENAME_FILEPATH3   VARCHAR2(50)      NULL,
   JFILES_ORIGINAL_FILEPATH4   VARCHAR2(50)      NULL,
   JFILES_RENAME_FILEPATH4   VARCHAR2(50)      NULL,
   JBOARD_CHECK   CHAR(1)   DEFAULT 'Y'   NOT NULL,
   JBOARD_MEET CHAR(1)   DEFAULT 'N'   NULL,
   JBOARD_POST   CHAR(1)   DEFAULT 'N'   NULL,
   MEMBER_ID   VARCHAR2(20)      NOT NULL,
   local_no   VARCHAR2(3)      NOT NULL
);

COMMENT ON COLUMN JBOARD.JBOARD_NO IS '�۹�ȣ';
COMMENT ON COLUMN JBOARD.JBOARD_TITLE IS '����';
COMMENT ON COLUMN JBOARD.JBOARD_CONTENT IS '��ǰ����';
COMMENT ON COLUMN JBOARD.JBOARD_PRICE IS '����';
COMMENT ON COLUMN JBOARD.JBOARD_DATE IS '�ۼ���';
COMMENT ON COLUMN JBOARD.JBOARD_UPDATE IS '������';
COMMENT ON COLUMN JBOARD.JBOARD_COUNT IS '��ȸ��';
COMMENT ON COLUMN JBOARD.JBOARD_LIKE IS '���ƿ��';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH1 IS '÷�����ϱ�����1';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH1 IS '÷�����Ϻ����1';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH2 IS '÷�����ϱ�����2';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH2 IS '÷�����Ϻ����2';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH3 IS '÷�����ϱ�����3';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH3 IS '÷�����Ϻ����3';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH4 IS '÷�����ϱ�����4';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH4 IS '÷�����Ϻ����4';
COMMENT ON COLUMN JBOARD.JBOARD_CHECK IS '�Խñ�ǥ�ÿ���';
COMMENT ON COLUMN JBOARD.JBOARD_MEET IS '���ŷ�';
COMMENT ON COLUMN JBOARD.JBOARD_POST IS '�����ŷ�';
COMMENT ON COLUMN JBOARD.MEMBER_ID IS 'ȸ�� ���̵�';
COMMENT ON COLUMN JBOARD.local_no IS '������ȣ';


ALTER TABLE JBOARD ADD CONSTRAINT PK_JBOARD PRIMARY KEY (JBOARD_NO);
ALTER TABLE JBOARD ADD CONSTRAINT FK_MEMBER_TO_JBOARD_1 FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE ;
ALTER TABLE JBOARD ADD CONSTRAINT FK_LOCATION_TO_JBOARD_1 FOREIGN KEY (local_no)
REFERENCES LOCATION (local_no);

<<<<<<< HEAD
<<<<<<< HEAD
=======
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_NO IS '��۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_ID IS '����ۼ���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_DATE IS '����ۼ���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_CONTENT IS '��۸��';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_PARENT IS '�θ��';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_LASTMODIFIED IS '������������';
COMMENT ON COLUMN JBOARD_COMMENT.JBOARD_NO IS '�۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_DEPTH IS '��۱���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_LEVEL IS '�۷���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REF IS '���й�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REPLY_REF IS '��۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REPLY_SEQ IS '��ۼ���';

CREATE SEQUENCE 
SEQ_JBOARD_NO
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE 
NOCACHE;

COMMIT;
>>>>>>> origin/member_home
=======
>>>>>>> origin/faq4
INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��������1','���ǳ���',14000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����2','��ǰ ���� 2',133000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����3','��ǰ ���� 3',13000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����4','��ǰ ���� 4',1300,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����5','��ǰ ���� 5',100,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����5','��ǰ ���� 5',133000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����6','��ǰ ���� 6',233000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����7','��ǰ ���� 7',533000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����8','��ǰ ���� 8',132000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����9','��ǰ ���� 9',33000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����10','��ǰ ���� 10',333000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����11','��ǰ ���� 11',133000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

COMMIT;

CREATE TABLE JBOARD_COMMENT (
   COMMENT_NO   NUMBER      NOT NULL,
   COMMENT_ID   VARCHAR2(20)      NOT NULL,
   COMMENT_CONTENT   VARCHAR2(1000)      NOT NULL,
    COMMENT_DATE   DATE   DEFAULT SYSDATE   NOT NULL,
   COMMENT_LASTMODIFIED   DATE   DEFAULT SYSDATE   NULL,
   JBOARD_NO   NUMBER      NOT NULL,
    COMMENT_REF NUMBER,
    COMMENT_REPLY_REF NUMBER,
    COMMENT_LEVEL NUMBER DEFAULT 0,
    COMMENT_REPLY_SEQ NUMBER DEFAULT 0
);
ALTER TABLE JBOARD_COMMENT ADD CONSTRAINT PK_BOARD_COMMENT PRIMARY KEY (COMMENT_NO);
ALTER TABLE JBOARD_COMMENT ADD CONSTRAINT FK_MEMBER_TO_JCOMMNET_1 FOREIGN KEY (COMMENT_ID)
REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE ;

COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_NO IS '��۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_ID IS '�ۼ���ID';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_DATE IS '��۳���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_CONTENT IS '��۵������';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_LASTMODIFIED IS '��ۼ�������';
COMMENT ON COLUMN JBOARD_COMMENT.JBOARD_NO IS '���۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_LEVEL IS '��۷���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REF IS '�����ġ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REPLY_REF IS '��۱���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REPLY_SEQ IS '��ۼ���';


CREATE SEQUENCE JBOARD_COMMENT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

commit;

--****************************************************************************************************

--��������
CREATE TABLE NOTICE(
    NO_NO NUMBER,
    NO_ID VARCHAR2(20) NOT NULL,
    NO_TITLE VARCHAR2(50) NOT NULL,
    NO_CONTENT VARCHAR2(4000) NOT NULL,
    NO_DATE DATE DEFAULT SYSDATE,
    NO_COUNT NUMBER DEFAULT 0,
    NO_ORIGINAL VARCHAR2(50),
    NO_RENAME VARCHAR2(50),
    
    CONSTRAINT PK_NNO PRIMARY KEY (NO_NO),
    CONSTRAINT FK_NID FOREIGN KEY (NO_ID) REFERENCES MEMBER ON DELETE SET NULL
);
COMMENT ON COLUMN NOTICE.NO_NO IS '�۹�ȣ';
COMMENT ON COLUMN NOTICE.NO_ID IS '�����ھ��̵�';
COMMENT ON COLUMN NOTICE.NO_TITLE IS '����';
COMMENT ON COLUMN NOTICE.NO_CONTENT IS '����';
COMMENT ON COLUMN NOTICE.NO_DATE IS '�ۼ���¥';
COMMENT ON COLUMN NOTICE.NO_COUNT IS '��ȸ��';
COMMENT ON COLUMN NOTICE.NO_ORIGINAL IS '������������';
COMMENT ON COLUMN NOTICE.NO_RENAME IS '����������';

INSERT INTO NOTICE VALUES(1, 'admin', '�������� �����Դϴ�.', '���������� ���� �����߽��ϴ�. ���� �̿����ּ���~', '2020/06/30', 5, null, null);
INSERT INTO NOTICE VALUES(2, 'admin', '��������1', '�߰��ŷ��� �� �������ּ���~', '2020/07/01', 3, null, null);
INSERT INTO NOTICE VALUES(3, 'admin', '��������2', 'Ŀ�´�Ƽ�� ���� �ø� �� ���� �����Դϴ�~', '2020/07/03', 1, null, null);
INSERT INTO NOTICE VALUES(4, 'admin', '��������3', '�Ű��� ���ϸ� ��������Ʈ�� �÷��� �� �ֽ��ϴ�. �������ּ���', '2020/07/03', 6, null, null);
INSERT INTO NOTICE VALUES(5, 'admin', '��������4', '��������Ʈ�� �÷����� �α��� ������ ���� �� �ֽ��ϴ�.', '2020/07/05', 10, null, null);
INSERT INTO NOTICE VALUES(6, 'admin', '��������5', '���������� ���� �����߽��ϴ�. ���� �̿����ּ���~', '2020/07/07', 5, null, null);
INSERT INTO NOTICE VALUES(7, 'admin', '��������6', '�߰��ŷ��� �� �������ּ���~', '2020/07/10', 3, null, null);
INSERT INTO NOTICE VALUES(8, 'admin', '��������7', 'Ŀ�´�Ƽ�� ���� �ø� �� ���� �����Դϴ�~', '2020/07/11', 1, null, null);
INSERT INTO NOTICE VALUES(9, 'admin', '��������8', '�Ű��� ���ϸ� ��������Ʈ�� �÷��� �� �ֽ��ϴ�. �������ּ���', '2020/07/13', 6, null, null);
INSERT INTO NOTICE VALUES(10, 'admin', '��������9', '��������Ʈ�� �÷����� �α��� ������ ���� �� �ֽ��ϴ�.', '2020/07/20', 10, null, null);
INSERT INTO NOTICE VALUES(11, 'admin', '��������10', '���������� ���� �����߽��ϴ�. ���� �̿����ּ���~', '2020/07/25', 5, null, null);
INSERT INTO NOTICE VALUES(12, 'admin', '��������11', '�߰��ŷ��� �� �������ּ���~', '2020/07/26', 3, null, null);
INSERT INTO NOTICE VALUES(13, 'admin', '��������12', 'Ŀ�´�Ƽ�� ���� �ø� �� ���� �����Դϴ�~', '2020/07/24', 1, null, null);
INSERT INTO NOTICE VALUES(14, 'admin', '��������13', '�Ű��� ���ϸ� ��������Ʈ�� �÷��� �� �ֽ��ϴ�. �������ּ���', '2020/07/27', 6, null, null);
INSERT INTO NOTICE VALUES(15, 'admin', '��������14', '��������Ʈ�� �÷����� �α��� ������ ���� �� �ֽ��ϴ�.', '2020/07/30', 10, null, null);

--���ֹ�������
CREATE TABLE FAQ(
    FAQ_NO NUMBER,
    FAQ_ID VARCHAR2(20) NOT NULL,
    FAQ_TITLE VARCHAR2(50) NOT NULL,
    FAQ_CONTENT VARCHAR2(4000) NOT NULL,
    FAQ_DATE DATE DEFAULT SYSDATE,
    FAQ_COUNT NUMBER DEFAULT 0,
    FAQ_CATEGORY NUMBER NOT NULL,
    
    CONSTRAINT PK_FNO PRIMARY KEY (FAQ_NO),
    CONSTRAINT FK_FID FOREIGN KEY (FAQ_ID) REFERENCES MEMBER ON DELETE SET NULL
);
COMMENT ON COLUMN FAQ.FAQ_NO IS '�۹�ȣ';
COMMENT ON COLUMN FAQ.FAQ_ID IS '������ ���̵�';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '����';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '����';
COMMENT ON COLUMN FAQ.FAQ_DATE IS '�ۼ���¥';
COMMENT ON COLUMN FAQ.FAQ_COUNT IS '��ȸ��';
COMMENT ON COLUMN FAQ.FAQ_CATEGORY IS 'ȸ��1, �߰�2, Ŀ��3, ����4';

INSERT INTO FAQ VALUES(1, 'admin', '�߰��ŷ��� � ����ΰ���?', '���ŷ� ����Դϴ�~', '2020/06/30', 5, 2);
INSERT INTO FAQ VALUES(2, 'admin', '�α����� ��� �ϳ���?', '������ ��� ���� �α��� ��ư�� �����ּ���~', '2020/07/01', 3, 1);
INSERT INTO FAQ VALUES(3, 'admin', '�α׾ƿ��� ��� �ϳ���?', '������ ��� ���� �α��� ��ư�� �����ּ���~', '2020/07/03', 1, 1);
INSERT INTO FAQ VALUES(4, 'admin', 'Ż��� ��� �ϳ���?', 'ȸ�������������������� Ż���ϱ� ��ư�� �����ּ���', '2020/07/03', 6, 1);
INSERT INTO FAQ VALUES(5, 'admin', '�������� ��� �����ϳ���', 'ȸ�������������������� �����ϱ� ��ư�� �����ּ���', '2020/07/05', 10, 1);
INSERT INTO FAQ VALUES(6, 'admin', '�߰��ŷ�~~', '�����Ҥ��ȿ������ˤ�������Ȩ���Ҥ���������������������', '2020/07/07', 5, 2);
INSERT INTO FAQ VALUES(7, 'admin', 'Ŀ�´�Ƽ~~', '�������������;�Ӥ��������������ߤ��ˤ����������ڷ�', '2020/07/10', 3, 3);
INSERT INTO FAQ VALUES(8, 'admin', 'Ŀ�´�Ƽ~~3', '~~~~~~~~���������������������ä�����������������������~~~~~~~~~~~~~~~', '2020/07/11', 1, 3);
INSERT INTO FAQ VALUES(9, 'admin', '��������', '~~~~~~~~����������������������~~~~~~��������������������������~~~~~~~~~', '2020/07/13', 6, 4);
INSERT INTO FAQ VALUES(10, 'admin', '��������123', '~~~~~~~~���������ȳ𤾤�����ȿ�~~~~~~~~~~~~~~~', '2020/07/20', 10, 4);
INSERT INTO FAQ VALUES(11, 'admin', '�߰��ŷ�32~~', '�����Ҥ��ȿ������ˤ�������Ȩ���Ҥ���������������������', '2020/07/23', 5, 2);
INSERT INTO FAQ VALUES(12, 'admin', 'Ŀ�´�Ƽ235~~', '�������������;�Ӥ��������������ߤ��ˤ����������ڷ�', '2020/07/24', 3, 3);
INSERT INTO FAQ VALUES(13, 'admin', 'Ŀ�´�Ƽ~~', '~~~~~~~~���������������������ä�����������������������~~~~~~~~~~~~~~~', '2020/07/12', 1, 3);
INSERT INTO FAQ VALUES(14, 'admin', '��������26', '~~~~~~~~����������������������~~~~~~��������������������������~~~~~~~~~', '2020/07/13', 6, 4);
INSERT INTO FAQ VALUES(15, 'admin', '��������98', '~~~~~~~~���������ȳ𤾤�����ȿ�~~~~~~~~~~~~~~~', '2020/07/26', 10, 4);

--���̺� ����
DROP TABLE IQTYPE CASCADE CONSTRAINTS;
--����
CREATE TABLE IQTYPE(
    IQ_TYPE VARCHAR2(20) CONSTRAINT PK_IQTYPE PRIMARY KEY
);
COMMENT ON COLUMN IQTYPE.IQ_TYPE IS '����';

INSERT INTO IQTYPE VALUES('ȸ������');
INSERT INTO IQTYPE VALUES('�߰��ŷ� �Ű�');
INSERT INTO IQTYPE VALUES('Ŀ�´�Ƽ �Ű�');
INSERT INTO IQTYPE VALUES('����');
INSERT INTO IQTYPE VALUES('�����ϱ�');
INSERT INTO IQTYPE VALUES('��Ÿ');

--���̺� ����
DROP TABLE INQUIRY CASCADE CONSTRAINTS;

--���ǰԽñ�
CREATE TABLE INQUIRY(
    IQ_NO NUMBER,
    IQ_ID VARCHAR2(20) CONSTRAINT FK_IQID REFERENCES MEMBER ON DELETE CASCADE,
    IQ_TITLE VARCHAR2(50) NOT NULL,
    IQ_CONTENT VARCHAR2(4000) NOT NULL,
    IQ_DATE DATE DEFAULT SYSDATE,
    IQ_ANSWER CHAR(1) DEFAULT 'N' NOT NULL CHECK (IQ_ANSWER = 'Y' OR IQ_ANSWER = 'N'),
    IQ_ORIGINAL VARCHAR2(50),
    IQ_RENAME VARCHAR2(50),
    IQ_ORIGINAL2 VARCHAR2(50),
    IQ_RENAME2 VARCHAR2(50),
    IQ_ORIGINAL3 VARCHAR2(50),
    IQ_RENAME3 VARCHAR2(50),
    IQ_TYPE VARCHAR2(20) NOT NULL CONSTRAINT FK_IQTYPE REFERENCES IQTYPE,
    CONSTRAINT PK_IQNOID PRIMARY KEY (IQ_NO, IQ_ID)
);
COMMENT ON COLUMN INQUIRY.IQ_NO IS '�۹�ȣ';
COMMENT ON COLUMN INQUIRY.IQ_ID IS 'ȸ�����̵�';
COMMENT ON COLUMN INQUIRY.IQ_TITLE IS '����';
COMMENT ON COLUMN INQUIRY.IQ_CONTENT IS '����';
COMMENT ON COLUMN INQUIRY.IQ_DATE IS '�ۼ���¥';
COMMENT ON COLUMN INQUIRY.IQ_ANSWER IS '�亯����';
COMMENT ON COLUMN INQUIRY.IQ_ORIGINAL IS '�������� ����';
COMMENT ON COLUMN INQUIRY.IQ_RENAME IS '������ ����';
COMMENT ON COLUMN INQUIRY.IQ_ORIGINAL2 IS '�������� ����2';
COMMENT ON COLUMN INQUIRY.IQ_RENAME2 IS '������ ����2';
COMMENT ON COLUMN INQUIRY.IQ_ORIGINAL3 IS '�������� ����3';
COMMENT ON COLUMN INQUIRY.IQ_RENAME3 IS '������ ����3';
COMMENT ON COLUMN INQUIRY.IQ_TYPE IS '����';

-- INSERT�Ϸ��� ���̵������� �ʿ��մϴ�~~~~~
INSERT INTO INQUIRY VALUES(1, 'user01', '�����Ҳ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/01', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(2, 'user08', 'ȸ������', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/02', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(3, 'user02', '�ȳ�~~', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/03', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(4, 'user03', 'Ż���ҷ���~', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/07', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(5, 'user01', 'ȸ������ �����ϰ��;��', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/09', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(6, 'user02', '�����ҷ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/12', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(7, 'user03', '�����ϰ� ������ ��� �ؿ�', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/14', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(8, 'user08', '�����߰��߾��', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/03', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(9, 'user01', '�˻������Դϴ�/', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/07', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(10, 'user02', 'ȸ�������Ϸ��µ� �ȵǳ׿�', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/07', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(11, 'user02', '������ 3���̻�ȵǳ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/16', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(12, 'user03', '�����Ҳ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/17', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '�����ϱ�');
INSERT INTO INQUIRY VALUES(13, 'user08', '��Ÿ���ǻ����Դϴ�.', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/18', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '��Ÿ');

--���̺� ����
DROP TABLE ANSWER CASCADE CONSTRAINTS;

--�亯�Խñ�
CREATE TABLE ANSWER(
    AN_NO NUMBER NOT NULL CONSTRAINT PK_ANNO PRIMARY KEY,
    AN_CONTENT VARCHAR2(4000) NOT NULL,
    AN_DATE DATE DEFAULT SYSDATE,
    IQ_NO NUMBER NOT NULL,
    IQ_ID VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_IQUNOID FOREIGN KEY (IQ_NO, IQ_ID) REFERENCES INQUIRY ON DELETE CASCADE
);
COMMENT ON COLUMN ANSWER.AN_NO IS '�۹�ȣ';
COMMENT ON COLUMN ANSWER.AN_CONTENT IS '����';
COMMENT ON COLUMN ANSWER.AN_DATE IS '�ۼ���¥';
COMMENT ON COLUMN ANSWER.IQ_NO IS '���۹�ȣ';
COMMENT ON COLUMN ANSWER.IQ_ID IS '�����ۼ���';

-- INSERT�Ϸ��� ���̵������� �ʿ��մϴ�~~~~~
INSERT INTO ANSWER VALUES(1, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/03', '3', 'user02');
INSERT INTO ANSWER VALUES(2, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/07', '4', 'user03');
INSERT INTO ANSWER VALUES(3, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/16', '12', 'user03');
INSERT INTO ANSWER VALUES(4, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/01', '13', 'user04');
INSERT INTO ANSWER VALUES(5, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/16', '10', 'user02');

COMMIT;

-- ���̺� ����
DROP TABLE DECLARE_BOARD CASCADE CONSTRAINTS;
-- �Ű� ���� �Խ��� ���̺� ����
CREATE TABLE DECLARE_BOARD (
   DECLARE_NO   NUMBER    CONSTRAINT PK_NO PRIMARY KEY,
   MEMBER_ID    VARCHAR2(20),
   DECLARE_TITLE    VARCHAR2(50) CONSTRAINT NN_BTITLE   NOT NULL,
   DECLARE_DATE    DATE DEFAULT SYSDATE,
   DECLARE_TYPE    VARCHAR2(20),
   DECLARE_CONTENT   VARCHAR2(4000),
   DECLARE_ORIGINAL   VARCHAR2(50),
   DECLARE_RENAME    VARCHAR2(50),
   DECLARE_URL    VARCHAR2(100),
   DECLARE_ID    VARCHAR2(20),   
       DECLARECHE  CHAR(1)   DEFAULT 'N'
);

COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "DECLARE_BOARD"."MEMBER_ID" IS '�ۼ���';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_TITLE" IS '������';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_DATE" IS '�����';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_TYPE" IS '�Ű�����';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_CONTENT" IS '����';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_ORIGINAL" IS '�������ϸ�';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_RENAME" IS '�������ϸ�';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_URL" IS '�ش��URL';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARECHE" IS '�Ű�ó��';

-- ��������
ALTER TABLE DECLARE_BOARD ADD CONSTRAINT FK_DECLARE_TYPE FOREIGN KEY (DECLARE_TYPE) REFERENCES IQTYPE(IQ_TYPE);
--������
INSERT INTO declare_board
VALUES(1, NULL,'�Ű��մϴ�.', DEFAULT, '�߰��ŷ� �Ű�', '������¥��ǰ���ΰŷ����մϴ�.','','','�߰��ŷ�URL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(2, NULL,'���۾��̵�Ű�.', DEFAULT, '�߰��ŷ� �Ű�', '���������۾��̵𿡿�.','','','�߰��ŷ�URL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(3, user01,'�����մϴ�.', DEFAULT, 'Ŀ�´�Ƽ �Ű�', '���ؿ�.','','',Ŀ�´�ƼURL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(4, user02,'�Ű��մϴ�.', DEFAULT, '�߰��ŷ� �Ű�', '������¥��ǰ���ΰŷ����մϴ�.','','','�߰��ŷ�URL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(5, user10,'���۾��̵�Ű�.', DEFAULT, '�߰��ŷ� �Ű�', '���������۾��̵𿡿�.','','','�߰��ŷ�URL', NULL, DEFAULT );
INSERT INTO declare_board
<<<<<<< HEAD
VALUES(3, user01,'�����մϴ�.', DEFAULT, 'Ŀ�´�Ƽ �Ű�', '���ؿ�.','','',Ŀ�´�ƼURL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(4, user02,'�Ű��մϴ�.', DEFAULT, '�߰��ŷ� �Ű�', '������¥��ǰ���ΰŷ����մϴ�.','','','�߰��ŷ�URL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(5, user10,'���۾��̵�Ű�.', DEFAULT, '�߰��ŷ� �Ű�', '���������۾��̵𿡿�.','','','�߰��ŷ�URL', NULL, DEFAULT );
INSERT INTO declare_board
VALUES(6, user08,'�����մϴ�.', DEFAULT, 'Ŀ�´�Ƽ �Ű�', '���ؿ�.','','','Ŀ�´�ƼURL', NULL, DEFAULT );
=======
VALUES(6, user08,'�����մϴ�.', DEFAULT, 'Ŀ�´�Ƽ �Ű�', '���ؿ�.','','','Ŀ�´�ƼURL', NULL, DEFAULT );
>>>>>>> origin/faq4



COMMIT;