--**********************************************************************************************************************
-- MEMBER ���̺� ����
DROP TABLE MEMBER CASCADE CONSTRAINTS;
-- MEMBER ���̺� ����
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(20) CONSTRAINT PKID PRIMARY KEY NOT NULL,
    MEMBER_PWD VARCHAR2(20) CONSTRAINT MPWD NOT NULL,
    MEMBER_NAME VARCHAR2(20) CONSTRAINT MNAME NOT NULL,
    MEMBER_ORIGINAL VARCHAR2(50) ,
    MEMBER_RENAME VARCHAR2(50) ,
    MEMBER_EMAIL VARCHAR2(20) CONSTRAINT MEMAIL NOT NULL,
    EmailAuth CHAR(1),
   MEMBER_PHONE   VARCHAR2(15) CONSTRAINT MPHONE NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE,
    LAST_ACCESS_DATE DATE DEFAULT SYSDATE
);

-- MEMBER �÷���
COMMENT ON COLUMN MEMBER.MEMBER_ID IS 'ȸ�� ���̵�';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS 'ȸ�� �н�����';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS 'ȸ�� �̸�';
COMMENT ON COLUMN MEMBER.MEMBER_ORIGINAL IS '÷�����ϱ�����';
COMMENT ON COLUMN MEMBER.MEMBER_RENAME IS '÷�����Ϻ����';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS 'ȸ�� �̸���';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '�̸�������';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS 'ȸ�� ��ȭ��ȣ';
COMMENT ON COLUMN MEMBER.JOIN_DATE IS '������';
COMMENT ON COLUMN MEMBER.LAST_ACCESS_DATE IS '�ֱ�������';

INSERT INTO MEMBER VALUES('admin01', 'admin01', '������', NULL, NULL, 'admin01@naver.com', NULL, '010-0000-0000', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('user01', 'user01', '�̼���', NULL, NULL, 'user01@naver.com', NULL, '010-1111-1111', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('user02', 'user02', '����', NULL, NULL, 'user02@naver.com', NULL, '010-2222-2222', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('user03', 'user03', '��ù�', NULL, NULL, 'user03@naver.com', NULL, '010-3333-3333', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('user04', 'user04', '������', NULL, NULL, 'user04@naver.com', NULL, '010-4444-4444', DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('user05', 'user05', '������', NULL, NULL, 'user05@naver.com', NULL, '010-5555-5555', DEFAULT, DEFAULT);


-- SECESSION ���̺� ����

DROP TABLE SECESSION CASCADE CONSTRAINTS;
-- SECESSION ���̺� ����
CREATE TABLE SECESSION (
    SECESSION_ID VARCHAR2(20) CONSTRAINT SMID PRIMARY KEY NOT NULL,
    SECESSION_PWD VARCHAR2(20) CONSTRAINT SMPWD NOT NULL,
    SECESSION_NAME VARCHAR2(20) CONSTRAINT SMNAME NOT NULL,
    SECESSION_EMAIL VARCHAR2(20) CONSTRAINT SMEMAIL NOT NULL UNIQUE,
   SECESSION_PHONE   VARCHAR2(15) CONSTRAINT SMPHONE NOT NULL UNIQUE,
    MJOIN_DATE DATE DEFAULT SYSDATE,
    SECESSION_DATE DATE DEFAULT SYSDATE
);

-- SECESSION �÷���
COMMENT ON COLUMN SECESSION.SECESSION_ID IS 'Ż��ȸ�� ���̵�';
COMMENT ON COLUMN SECESSION.SECESSION_PWD IS 'Ż��ȸ�� �н�����';
COMMENT ON COLUMN SECESSION.SECESSION_NAME IS 'Ż��ȸ�� �̸�';
COMMENT ON COLUMN SECESSION.SECESSION_EMAIL IS 'Ż��ȸ�� �̸���';
COMMENT ON COLUMN SECESSION.SECESSION_PHONE IS 'Ż��ȸ�� ��ȭ��ȣ';
COMMENT ON COLUMN SECESSION.MJOIN_DATE IS '������';
COMMENT ON COLUMN SECESSION.SECESSION_DATE IS 'Ż����';

INSERT INTO SECESSION VALUES('user06', 'user06', '�����', 'user06@naver.com', '010-6666-6666', DEFAULT, DEFAULT);
INSERT INTO SECESSION VALUES('user07', 'user07', '�Ÿ�', 'user07@naver.com', '010-7777-7777', DEFAULT, DEFAULT);

COMMIT;

--**********************************************************************************************************************


-- ���̺� ����
DROP TABLE BANNER  CASCADE CONSTRAINTS;
-- ��� ���� ���̺� ����
CREATE TABLE BANNER (
	BANNER_NO	 NUMBER CONSTRAINT PK_BA PRIMARY KEY,
	BANNER_TITLE	VARCHAR2(50)	 CONSTRAINT NN_TITLE NOT NULL,
	BANNER_CHK	CHAR(1)	DEFAULT 'H',
	BANNER_OK	CHAR(1)	DEFAULT 'Y',	
	BANNER_ORIGINAL	VARCHAR2(50)	 CONSTRAINT NN_ORIGINAL NOT NULL,
	BANNER_RENAME	VARCHAR2(50),
	BANNER_SIZE	VARCHAR2(20),
    CONSTRAINT CHK_BAO CHECK (BANNER_OK IN ('Y','N')),
    CONSTRAINT CHK_BAC CHECK (BANNER_CHK IN ('H','W'))
);

COMMENT ON COLUMN "BANNER"."BANNER_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "BANNER"."BANNER_TITLE" IS '�������';
COMMENT ON COLUMN "BANNER"."BANNER_CHK" IS '�Խù�ʰ���';
COMMENT ON COLUMN "BANNER"."BANNER_OK" IS '�Խÿ���Ȯ��';
COMMENT ON COLUMN "BANNER"."BANNER_ORIGINAL" IS '�������ϸ�';
COMMENT ON COLUMN "BANNER"."BANNER_RENAME" IS '�ٲ����ϸ�';
COMMENT ON COLUMN "BANNER"."BANNER_SIZE" IS '������';


-- ���̺� ����
DROP TABLE DECLARE_ADMIN CASCADE CONSTRAINTS;
-- �Ű��� ���� ���̺� ����
CREATE TABLE DECLARE_ADMIN (
	DECLARE_NO NUMBER	 CONSTRAINT PK_DNO PRIMARY KEY,
	DECLARE_ID	VARCHAR2(20)		CONSTRAINT NN_ID NOT NULL,
	DECLARE_COUNT	NUMBER		CONSTRAINT NN_COUNT  NOT NULL,
	DECLARE_OK CHAR(1)	DEFAULT 'N'	CONSTRAINT NN_OK NOT NULL,
    CONSTRAINT CHK_DOK CHECK (DECLARE_OK IN ('Y','N'))
);

COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_NO" IS '����';
COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_ID" IS '�Ű�ȸ��';
COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_COUNT" IS '�Ű���� Ƚ��';
COMMENT ON COLUMN "DECLARE_ADMIN"."DECLARE_OK" IS '���Ѽ���';

ALTER TABLE DECLARE_ADMIN ADD CONSTRAINT FK_DECLARE_ID FOREIGN KEY(DECLARE_ID) REFERENCES MEMBER(MEMBER_ID);

INSERT INTO DECLARE_ADMIN VALUES(1, 'user05', 2, 'N');
INSERT INTO DECLARE_ADMIN VALUES(2, 'user01', 1, 'N');
INSERT INTO DECLARE_ADMIN VALUES(3, 'user03', 4, 'N');

COMMIT;

-- ���� ������ ��� ���̵� ��ȸ�� ����� ������
SELECT MEMBER_ID, DECLARE_OK FROM MEMBER 
LEFT JOIN DECLARE_ADMIN ON(MEMBER_ID = DECLARE_ID)
where declare_ok='Y';

-- ���̺� ����
DROP TABLE DECLARE_BOARD CASCADE CONSTRAINTS;
-- �Ű� ���� �Խ��� ���̺� ����
CREATE TABLE DECLARE_BOARD (
	DECLARE_NO	NUMBER	 CONSTRAINT PK_NO PRIMARY KEY,
	MEMBER_ID	 VARCHAR2(20),
	DECLARE_TITLE	 VARCHAR2(50) CONSTRAINT NN_BTITLE	NOT NULL,
	DECLARE_DATE	 DATE DEFAULT SYSDATE,
	DECLARE_TYPE 	VARCHAR2(20),
	DECLARE_CONTENT	VARCHAR2(4000)	CONSTRAINT NN_CONTENT NOT NULL,
	DECLARE_ORIGINAL	VARCHAR2(50),
	DECLARE_RENAME	 VARCHAR2(50),
	DECLARE_URL	 VARCHAR2(100) CONSTRAINT NN_URL NOT NULL,
	DECLARE_ID	 VARCHAR2(20)	
);

COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "DECLARE_BOARD"."MEMBER_ID" IS '�ۼ���';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_TITLE" IS '������';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_DATE" IS '�����';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_TYPE" IS '�Ű�����';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_CONTENT" IS '����';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_ORIGINAL" IS '�������ϸ�';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_RENAME" IS '�������ϸ�';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_URL" IS '�ش��URL';
COMMENT ON COLUMN "DECLARE_BOARD"."DECLARE_ID" IS '��ȸ��ID';


INSERT INTO declare_board
VALUES(1, NULL,'�Ű��մϴ�.', DEFAULT, '�߰�ŷ��Ű�', '������¥��ǰ���ΰŷ����մϴ�.','','','�߰�ŷ�URL', NULL );
INSERT INTO declare_board
VALUES(2, NULL,'���۾��̵�Ű�.', DEFAULT, '�߰�ŷ��Ű�', '���������۾��̵𿡿�.','','','�߰�ŷ�URL', NULL );
INSERT INTO declare_board
VALUES(3, NULL,'�����մϴ�.', DEFAULT, 'Ŀ�´�Ƽ�Ű�', '���ؿ�.','','','�߰�ŷ�URL', NULL );


INSERT INTO BANNER
VALUES(1, '����', DEFAULT, DEFAULT, 'MAIIN.jpg', '', '1080x350' );
INSERT INTO BANNER
VALUES(2, 'sky', DEFAULT, DEFAULT, 'sky.jpg', '', '1080x350' );
INSERT INTO BANNER
VALUES(3, 'bless', DEFAULT, DEFAULT, 'visual.jpg', '', '1920x740' );

COMMIT;



-- ���� �з�
DROP TABLE LOCATION CASCADE CONSTRAINTS;    --���̺� ����

CREATE TABLE LOCATION (
	local_no	VARCHAR2(3)		NOT NULL,   -- PK
	local_name	VARCHAR2(20)		NOT NULL,
	kmap_y	VARCHAR2(30)		NULL,
    kmap_x	VARCHAR2(30)		NULL,
    CONSTRAINT PK_local_no PRIMARY KEY (local_no)
);

COMMENT ON COLUMN LOCATION.local_no IS '������ȣ';
COMMENT ON COLUMN LOCATION.local_name IS '�����̸�(��)';
COMMENT ON COLUMN LOCATION.kmap_y IS '������ �߽� ��ġ ����';
COMMENT ON COLUMN LOCATION.kmap_x IS '������ �߽� ��ġ �浵';

-- ���� ������ ����
INSERT INTO LOCATION(local_no, local_name, kmap_y, kmap_x)
SELECT '1', '������', '37.4959854', '127.0664091' FROM DUAL UNION ALL
SELECT '2', '������', '37.5492077', '127.1464824' FROM DUAL UNION ALL
SELECT '3', '���ϱ�', '37.6469954', '127.0147158' FROM DUAL UNION ALL
SELECT '4', '������', '37.5657617', '126.8226561' FROM DUAL UNION ALL
SELECT '5', '���Ǳ�', '37.4653993', '126.9438071' FROM DUAL UNION ALL
SELECT '6', '������', '37.5481445', '127.0857528' FROM DUAL UNION ALL
SELECT '7', '���α�', '37.4954856', '126.858121' FROM DUAL UNION ALL
SELECT '8', '��õ��', '37.4600969', '126.9001546' FROM DUAL UNION ALL
SELECT '9', '�����', '37.655264', '127.0771201' FROM DUAL UNION ALL
SELECT '10', '������', '37.6658609', '127.0317674' FROM DUAL UNION ALL
SELECT '11', '���빮��', '37.5838012', '127.0507003' FROM DUAL UNION ALL
SELECT '12', '���۱�', '37.4965037', '126.9443073' FROM DUAL UNION ALL
SELECT '13', '������', '37.5622906', '126.9087803' FROM DUAL UNION ALL
SELECT '14', '���빮��', '37.5820369', '126.9356665' FROM DUAL UNION ALL
SELECT '15', '���ʱ�', '37.4769528', '127.0378103' FROM DUAL UNION ALL
SELECT '16', '������', '37.5506753', '127.0409622' FROM DUAL UNION ALL
SELECT '17', '���ϱ�' ,'37.606991', '127.0232185' FROM DUAL UNION ALL
SELECT '18', '���ı�' ,'37.5048534', '127.1144822' FROM DUAL UNION ALL
SELECT '19', '��õ��', '37.5270616', '126.8561534' FROM DUAL UNION ALL
SELECT '20', '��������', '37.520641', '126.9139242' FROM DUAL UNION ALL
SELECT '21', '��걸', '37.5311008', '126.9810742' FROM DUAL UNION ALL
SELECT '22', '����', '37.6176125', '126.9227004' FROM DUAL UNION ALL
SELECT '23', '���α�', '37.5990998', '126.9861493' FROM DUAL UNION ALL
SELECT '24', '�߱�', '37.5579452', '126.9941904' FROM DUAL UNION ALL
SELECT '25', '�߶���', '37.5953795', '127.0939669' FROM DUAL;

COMMIT;

-- ���� ����
DROP TABLE FESTIVAL_INFORMATION CASCADE CONSTRAINTS;    --���̺� ����
CREATE TABLE FESTIVAL_INFORMATION (
	festival_no	VARCHAR2(12)		NOT NULL,   -- PK
	local_no	VARCHAR2(3)		NOT NULL,   -- FK : LOCATION(local_no)
	festival_title	VARCHAR2(600)		NOT NULL,
	area_code	VARCHAR2(3)		NULL,
    map_y	VARCHAR2(30)		NULL,
	map_x	VARCHAR2(30)		NULL,
	addr1	VARCHAR2(400)		NULL,
	addr2	VARCHAR2(400)		NULL,
	festival_startdate	VARCHAR2(8)		NOT NULL,
	festival_enddate	VARCHAR2(8)		NOT NULL,
	festival_place	VARCHAR2(500)		NULL,
	festival_homepage	VARCHAR2(4000)		NULL,
	sponsor	VARCHAR2(300)		NULL,
	sponsor_tel	VARCHAR2(300)		NULL,
	overview	VARCHAR2(4000)		NULL,
	image_original	VARCHAR2(1000)		NULL,
	image_thumbnail	VARCHAR2(1000)		NULL,
	fcreate_date	VARCHAR2(14)		NULL,
	fmodify_date	VARCHAR2(14)		NULL,
	festival_playtime	VARCHAR2(4000)		NULL,
     CONSTRAINT PK_festival_no PRIMARY KEY (festival_no)
);

COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_no IS '������ȣ';
COMMENT ON COLUMN FESTIVAL_INFORMATION.local_no IS '������ȣ2';
COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_title IS '������';
COMMENT ON COLUMN FESTIVAL_INFORMATION.area_code IS '������ȣ1';
COMMENT ON COLUMN FESTIVAL_INFORMATION.map_y IS '����';
COMMENT ON COLUMN FESTIVAL_INFORMATION.map_x IS '�浵';
COMMENT ON COLUMN FESTIVAL_INFORMATION.addr1 IS '�ּ�';
COMMENT ON COLUMN FESTIVAL_INFORMATION.addr2 IS '���ּ�';
COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_startdate IS '���� ������';
COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_enddate IS '���� ������';
COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_place IS '���� ���';
COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_homepage IS 'Ȩ������ �ּ�';
COMMENT ON COLUMN FESTIVAL_INFORMATION.sponsor IS '�ְ��� ����';
COMMENT ON COLUMN FESTIVAL_INFORMATION.sponsor_tel IS '�ְ��� ����ó';
COMMENT ON COLUMN FESTIVAL_INFORMATION.overview IS '����';
COMMENT ON COLUMN FESTIVAL_INFORMATION.image_original IS '�̹���(����)';
COMMENT ON COLUMN FESTIVAL_INFORMATION.image_thumbnail IS '�̹���(�����)';
COMMENT ON COLUMN FESTIVAL_INFORMATION.fcreate_date IS '���� �����';
COMMENT ON COLUMN FESTIVAL_INFORMATION.fmodify_date IS '���� ������';
COMMENT ON COLUMN FESTIVAL_INFORMATION.festival_playtime IS '���� �ð�';


-- ���� �Խ���
DROP TABLE FBOARD CASCADE CONSTRAINTS;    -- ���̺� ����

CREATE TABLE FBOARD (
	fboard_no	NUMBER		NOT NULL,   -- PK
	festival_no	VARCHAR2(12)		NOT NULL,   -- FK : FESTIVAL_INFORMATION(festival_no)
	MEMBER_ID	VARCHAR2(20)		NOT NULL,    -- FK : MEMBER(MEMBER_ID)
	bmodify_date	DATE	DEFAULT SYSDATE	NULL,
	bcreate_date	DATE	DEFAULT SYSDATE	NULL,
	readcount	NUMBER	DEFAULT 0 	NULL,
	statement_date	CHAR(1)	DEFAULT 'V'	NULL,   -- CHECK : V(view ���̱�) or W(window â���� �˷��ֱ�) or D(delete �����ϱ�)
    CONSTRAINT PK_fboard_no PRIMARY KEY (fboard_no),
    CONSTRAINT CK_statement_date CHECK (statement_date IN('V', 'W', 'D'))
);

COMMENT ON COLUMN FBOARD.fboard_no IS '�Խ��� ��ȣ';
COMMENT ON COLUMN FBOARD.festival_no IS '������ȣ';
COMMENT ON COLUMN FBOARD.MEMBER_ID IS '������ID';
COMMENT ON COLUMN FBOARD.bmodify_date IS '�Խñ� ���� ��¥';
COMMENT ON COLUMN FBOARD.bcreate_date IS '�Խñ� ��� ��¥';
COMMENT ON COLUMN FBOARD.readcount IS '��ȸ��';
COMMENT ON COLUMN FBOARD.statement_date IS '�����Ⱓ ���� Ȯ��';

-- ���� �Խ��� ���
DROP TABLE FBOARD_COMMENT CASCADE CONSTRAINTS;    -- ���̺� ����

CREATE TABLE FBOARD_COMMENT (
	fcomment_no 	NUMBER		NOT NULL,   -- PK
	fboard_no	NUMBER		NOT NULL,   -- FK : FBOARD(fboard_no)
	MEMBER_ID	VARCHAR2(20)		NOT NULL,  
	comment_date	DATE	DEFAULT SYSDATE	NOT NULL,
	comment_content	VARCHAR2(1000)		NOT NULL,
    CONSTRAINT PK_fcomment_no PRIMARY KEY (fcomment_no)
);

COMMENT ON COLUMN FBOARD_COMMENT.fcomment_no IS '��� ��ȣ';
COMMENT ON COLUMN FBOARD_COMMENT.fboard_no IS '�Խ��� ��ȣ';
COMMENT ON COLUMN FBOARD_COMMENT.MEMBER_ID IS '�ۼ��� ���̵�';
COMMENT ON COLUMN FBOARD_COMMENT.comment_date IS '�ۼ���¥';
COMMENT ON COLUMN FBOARD_COMMENT.comment_content IS '��� ����';

--FK ����
ALTER TABLE FESTIVAL_INFORMATION ADD CONSTRAINT FK_local_no FOREIGN KEY(local_no) REFERENCES LOCATION(local_no);    -- LOCATION(local_no)
ALTER TABLE FBOARD ADD CONSTRAINT FK_festival_no FOREIGN KEY(festival_no) REFERENCES FESTIVAL_INFORMATION(festival_no) ON DELETE CASCADE;  -- FESTIVAL_INFORMATION(festival_no), ���� ���� ���� �� ���� �Խ��ǵ� ����
ALTER TABLE FBOARD ADD CONSTRAINT FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID); -- MEMBER(MEMBER_ID) 
ALTER TABLE FBOARD_COMMENT ADD CONSTRAINT FK_fboard_no FOREIGN KEY(fboard_no) REFERENCES FBOARD(fboard_no) ON DELETE CASCADE;   -- FBOARD(fboard_no),  ���� �Խ��� ���� �� ��۵� ����

-- ���� ���� ������ �ֱ�
INSERT INTO FESTIVAL_INFORMATION(festival_no, local_no, festival_title, festival_startdate, festival_enddate)
SELECT '325311', '1', '���������� ������', SYSDATE, SYSDATE FROM DUAL UNION ALL
SELECT '768712', '2', '�̹� �ָ� �ʹ� ����ڴ�', SYSDATE, SYSDATE FROM DUAL UNION ALL
SELECT '659873', '3', '������ ���ϱ��Դϴ�.', SYSDATE, SYSDATE FROM DUAL UNION ALL
SELECT '213454', '4', '�̹������� ������ �Դϴ�. 37.5657617126.8226561', SYSDATE, SYSDATE FROM DUAL;

INSERT INTO FESTIVAL_INFORMATION(festival_no, local_no, festival_title, festival_startdate, festival_enddate)
VALUES('135486', '5', '�ް� Ŀ�� �ʹ� ���ִ�', sysdate, sysdate);

-- �Խ��� ���� �ֱ�
INSERT INTO FBOARD(fboard_no, festival_no, member_id, bcreate_date, bmodify_date)
SELECT '325311', '325311', 'admin01', SYSDATE, SYSDATE FROM DUAL UNION ALL
SELECT '768712', '768712', 'admin01', SYSDATE, SYSDATE FROM DUAL UNION ALL
SELECT '659873', '659873', 'admin01', SYSDATE ,SYSDATE FROM DUAL;

INSERT INTO FBOARD(fboard_no, festival_no, member_id, bcreate_date, bmodify_date)
VALUES('213454', '213454', 'admin01', sysdate, sysdate);

--**********************************************************************************************************************

--Ŀ�´�Ƽ
DROP SEQUENCE CBOARD_SEQ;
DROP SEQUENCE CREPLY_SEQ;
DROP TABLE CBOARD CASCADE CONSTRAINTS;
DROP TABLE CREPLY CASCADE CONSTRAINTS;

CREATE SEQUENCE CBOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE CREPLY_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE CBOARD (
	"CBOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CBOARD_TITLE"	VARCHAR2(50)		NOT NULL,
	"CBOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CBOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CBOARD_LASTMODIFIED"	DATE	DEFAULT SYSDATE	NULL,
	"CBOARD_VIEWCOUNT"	NUMBER	DEFAULT 0	NULL,
	"CBOARD_REPLYCOUNT"	NUMBER	DEFAULT 0	NULL,
	"CBOARD_LIKECOUNT"	NUMBER	DEFAULT 0	NULL,
	"CBOARD_REPORTCOUNT"	NUMBER	DEFAULT 0	NULL,
	"CBOARD_DISPLAY"	CHAR(1)	DEFAULT 'Y'	NULL,
	"LOCAL_NO"	VARCHAR2(3)		NULL,
	"CFILES_ORIGINAL_FILEPATH1"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH1"	VARCHAR2(50)		NULL,
	"CFILES_ORIGINAL_FILEPATH2"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH2"	VARCHAR2(50)		NULL,
	"CFILES_ORIGINAL_FILEPATH3"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH3"	VARCHAR2(50)		NULL,
	"CFILES_ORIGINAL_FILEPATH4"	VARCHAR2(50)		NULL,
	"CFILES_RENAME_FILEPATH4"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "CBOARD"."CBOARD_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "CBOARD"."MEMBER_ID" IS 'ȸ�� ���̵�';
COMMENT ON COLUMN "CBOARD"."CBOARD_TITLE" IS '������';
COMMENT ON COLUMN "CBOARD"."CBOARD_CONTENT" IS '�۳���';
COMMENT ON COLUMN "CBOARD"."CBOARD_DATE" IS '�ۼ���';
COMMENT ON COLUMN "CBOARD"."CBOARD_LASTMODIFIED" IS '������������';
COMMENT ON COLUMN "CBOARD"."CBOARD_VIEWCOUNT" IS '��ȸ��';
COMMENT ON COLUMN "CBOARD"."CBOARD_REPLYCOUNT" IS '��ۼ�';
COMMENT ON COLUMN "CBOARD"."CBOARD_LIKECOUNT" IS '���ƿ��';
COMMENT ON COLUMN "CBOARD"."CBOARD_REPORTCOUNT" IS '�Ű��';
COMMENT ON COLUMN "CBOARD"."CBOARD_DISPLAY" IS '��ǥ�ÿ���';
COMMENT ON COLUMN "CBOARD"."LOCAL_NO" IS '������ȣ';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH1" IS '�������ϸ�1';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH1" IS '�������ϸ�1';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH2" IS '�������ϸ�2';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH2" IS '�������ϸ�2';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH3" IS '�������ϸ�3';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH3" IS '�������ϸ�3';
COMMENT ON COLUMN "CBOARD"."CFILES_ORIGINAL_FILEPATH4" IS '�������ϸ�4';
COMMENT ON COLUMN "CBOARD"."CFILES_RENAME_FILEPATH4" IS '�������ϸ�4';

CREATE TABLE CREPLY (
	"CREPLY_NO"	NUMBER		NOT NULL,
	"CBOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"CREPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CREPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"PARANT_REPLY"	NUMBER		NULL,
	"CREPLY_ORDER"	NUMBER		NULL,
	"CREPLY_DEPTH"	NUMBER		NULL
);

COMMENT ON COLUMN "CREPLY"."CREPLY_NO" IS '��۹�ȣ';
COMMENT ON COLUMN "CREPLY"."CBOARD_NO" IS '�۹�ȣ';
COMMENT ON COLUMN "CREPLY"."MEMBER_ID" IS 'ȸ�� ���̵�';
COMMENT ON COLUMN "CREPLY"."CREPLY_DATE" IS '�ۼ���';
COMMENT ON COLUMN "CREPLY"."CREPLY_CONTENT" IS '��۳���';
COMMENT ON COLUMN "CREPLY"."PARANT_REPLY" IS '�θ��۹�ȣ';
COMMENT ON COLUMN "CREPLY"."CREPLY_ORDER" IS '��ۼ���';
COMMENT ON COLUMN "CREPLY"."CREPLY_DEPTH" IS '��۱���';

ALTER TABLE CBOARD ADD CONSTRAINT PK_CBOARD PRIMARY KEY (CBOARD_NO);
ALTER TABLE CREPLY ADD CONSTRAINT PK_CREPLY PRIMARY KEY (CREPLY_NO);
ALTER TABLE CBOARD ADD CONSTRAINT CHK_COBARD_DISPLAY CHECK (CBOARD_DISPLAY IN ('Y', 'N'));
ALTER TABLE "CBOARD" ADD CONSTRAINT "FK_MEMBER_TO_CBOARD" FOREIGN KEY(MEMBER_ID)REFERENCES MEMBER (MEMBER_ID);
ALTER TABLE "CBOARD" ADD CONSTRAINT "FK_LOCATION_TO_CBOARD" FOREIGN KEY (LOCAL_NO)REFERENCES LOCATION (LOCAL_NO);
ALTER TABLE "CREPLY" ADD CONSTRAINT "FK_CBOARD_TO_CREPLY" FOREIGN KEY (CBOARD_NO)REFERENCES CBOARD (CBOARD_NO);
ALTER TABLE "CREPLY" ADD CONSTRAINT "FK_MEMBER_TO_CREPLY" FOREIGN KEY (MEMBER_ID)REFERENCES MEMBER (MEMBER_ID);

commit;

-- sample data
INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', 'ù��° �Խñ�', 'ù��° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�ι�° �Խñ�', '�ι�° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '����° �Խñ�', '����° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�׹�° �Խñ�', '�׹�° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user01', '�ټ���° �Խñ�', '�ټ���° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '������° �Խñ�', '������° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '�ϰ���° �Խñ�', '�ϰ���° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '������° �Խñ�', '������° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '��ȩ��° �Խñ�', '��ȩ��° ����', DEFAULT);

INSERT INTO CBOARD(CBOARD_NO, MEMBER_ID, CBOARD_TITLE, CBOARD_CONTENT, CBOARD_DATE) 
VALUES(CBOARD_SEQ.NEXTVAL, 'user02', '����° �Խñ�', '����° ����', DEFAULT);

-- sample data
INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 1, 'user01', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 2, 'user01', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 3, 'user01', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 4, 'user01', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 5, 'user01', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 6, 'user02', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 7, 'user02', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 8, 'user02', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 9, 'user02', DEFAULT, 'ù��° ����');

INSERT INTO CREPLY(CREPLY_NO, CBOARD_NO, MEMBER_ID, CREPLY_DATE, CREPLY_CONTENT) 
VALUES(CREPLY_SEQ.NEXTVAL, 10, 'user05', DEFAULT, 'ù��° ����');

commit;

--**********************************************************************************************************************

--�߰�ŷ���Ʈ
DROP TABLE JBOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE JBOARD CASCADE CONSTRAINTS;


CREATE TABLE JBOARD (
	JBOARD_NO	NUMBER		NOT NULL,
	JBOARD_TITLE	VARCHAR2(50)		NOT NULL,
	JBOARD_CONTENT	VARCHAR2(4000)		NOT NULL,
	JBOARD_PRICE	NUMBER		NOT NULL,
	JBOARD_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	JBOARD_UPDATE	DATE	DEFAULT SYSDATE	NULL,
	JBOARD_COUNT	NUMBER	DEFAULT 0	NULL,
	JBOARD_LIKE	NUMBER	DEFAULT 0	NULL,
	JFILES_ORIGINAL_FILEPATH1	VARCHAR2(50)		NULL,
	JFILES_RENAME_FILEPATH1	VARCHAR2(50)		NULL,
	JFILES_ORIGINAL_FILEPATH2	VARCHAR2(50)		NULL,
	JFILES_RENAME_FILEPATH2	VARCHAR2(50)		NULL,
	JFILES_ORIGINAL_FILEPATH3	VARCHAR2(50)		NULL,
	JFILES_RENAME_FILEPATH3	VARCHAR2(50)		NULL,
	JFILES_ORIGINAL_FILEPATH4	VARCHAR2(50)		NULL,
	JFILES_RENAME_FILEPATH4	VARCHAR2(50)		NULL,
	JBOARD_CHECK	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	JBOARD_MEET CHAR(1)	DEFAULT 'N'	NULL,
	JBOARD_POST	CHAR(1)	DEFAULT 'N'	NULL,
	MEMBER_ID	VARCHAR2(20)		NOT NULL,
	local_no	VARCHAR2(3)		NOT NULL
);

COMMENT ON COLUMN JBOARD.JBOARD_NO IS '�۹�ȣ';
COMMENT ON COLUMN JBOARD.JBOARD_TITLE IS '����';
COMMENT ON COLUMN JBOARD.JBOARD_CONTENT IS '��ǰ����';
COMMENT ON COLUMN JBOARD.JBOARD_PRICE IS '����';
COMMENT ON COLUMN JBOARD.JBOARD_DATE IS '�ۼ���';
COMMENT ON COLUMN JBOARD.JBOARD_UPDATE IS '������';
COMMENT ON COLUMN JBOARD.JBOARD_COUNT IS '��ȸ��';
COMMENT ON COLUMN JBOARD.JBOARD_LIKE IS '���ƿ��';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH1 IS '÷�����ϱ�����1';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH1 IS '÷�����Ϻ����1';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH2 IS '÷�����ϱ�����2';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH2 IS '÷�����Ϻ����2';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH3 IS '÷�����ϱ�����3';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH3 IS '÷�����Ϻ����3';
COMMENT ON COLUMN JBOARD.JFILES_ORIGINAL_FILEPATH4 IS '÷�����ϱ�����4';
COMMENT ON COLUMN JBOARD.JFILES_RENAME_FILEPATH4 IS '÷�����Ϻ����4';
COMMENT ON COLUMN JBOARD.JBOARD_CHECK IS '�Խñ�ǥ�ÿ���';
COMMENT ON COLUMN JBOARD.JBOARD_MEET IS '���ŷ�';
COMMENT ON COLUMN JBOARD.JBOARD_POST IS '����ŷ�';
COMMENT ON COLUMN JBOARD.MEMBER_ID IS 'ȸ�� ���̵�';
COMMENT ON COLUMN JBOARD.local_no IS '������ȣ';


ALTER TABLE JBOARD ADD CONSTRAINT PK_JBOARD PRIMARY KEY (JBOARD_NO);
ALTER TABLE JBOARD ADD CONSTRAINT FK_MEMBER_TO_JBOARD_1 FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE ;
ALTER TABLE JBOARD ADD CONSTRAINT FK_LOCATION_TO_JBOARD_1 FOREIGN KEY (local_no)
REFERENCES LOCATION (local_no);
COMMIT;
CREATE TABLE JBOARD_COMMENT (
	COMMENT_NO	NUMBER		NOT NULL,
	COMMENT_ID	VARCHAR2(20)		NOT NULL,
	COMMENT_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	COMMENT_CONTENT	VARCHAR2(1000)		NOT NULL,
	COMMENT_PARENT	NUMBER		NULL,
	COMMENT_LASTMODIFIED	DATE	DEFAULT SYSDATE	NULL,
	JBOARD_NO	NUMBER		NOT NULL,
	COMMENT_DEPTH	NUMBER		NULL,
	COMMENT_ORDER	NUMBER		NULL,
    COMMENT_LEVEL NUMBER DEFAULT 0,
    COMMENT_REF NUMBER,
    COMMENT_REPLY_REF NUMBER,
    COMMENT_REPLY_SEQ NUMBER DEFAULT 0
);

ALTER TABLE JBOARD_COMMENT ADD CONSTRAINT PK_BOARD_COMMENT PRIMARY KEY (COMMENT_NO);
ALTER TABLE JBOARD_COMMENT ADD CONSTRAINT FK_MEMBER_TO_JCOMMNET_1 FOREIGN KEY (COMMENT_ID)
REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE ;

COMMIT;

COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_NO IS '��۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_ID IS '����ۼ���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_DATE IS '����ۼ���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_CONTENT IS '��۸��';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_PARENT IS '�θ��';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_LASTMODIFIED IS '������������';
COMMENT ON COLUMN JBOARD_COMMENT.JBOARD_NO IS '�۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_DEPTH IS '��۱���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_LEVEL IS '�۷���';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REF IS '���й�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REPLY_REF IS '��۹�ȣ';
COMMENT ON COLUMN JBOARD_COMMENT.COMMENT_REPLY_SEQ IS '��ۼ���';

CREATE SEQUENCE 
SEQ_JBOARD_NO
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE 
NOCACHE;

COMMIT;
INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��������1','���ǳ���',14000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����2','��ǰ ���� 2',133000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����3','��ǰ ���� 3',13000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����4','��ǰ ���� 4',1300,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����5','��ǰ ���� 5',100,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����5','��ǰ ���� 5',133000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����6','��ǰ ���� 6',233000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����7','��ǰ ���� 7',533000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����8','��ǰ ���� 8',132000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����9','��ǰ ���� 9',33000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����10','��ǰ ���� 10',333000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

INSERT INTO JBOARD VALUES
(SEQ_JBOARD_NO.nextval,'��ǰ�� ����11','��ǰ ���� 11',133000,SYSDATE,SYSDATE,DEFAULT,DEFAULT,NULL,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,DEFAULT,DEFAULT,DEFAULT,'admin01', 1);

-- �߰�ŷ����
INSERT INTO JBOARD_COMMENT VALUES
(1,'admin01',SYSDATE,'�̰��� ���',1,SYSDATE,1,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(2,'admin01',SYSDATE,'�̰��� ���',2,SYSDATE,2,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(3,'admin01',SYSDATE,'�̰��� ���',3,SYSDATE,3,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(4,'admin01',SYSDATE,'�̰��� ���',4,SYSDATE,4,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(5,'admin01',SYSDATE,'�̰��� ���',5,SYSDATE,5,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(6,'admin01',SYSDATE,'�̰��� ���',6,SYSDATE,6,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(7,'admin01',SYSDATE,'�̰��� ���',7,SYSDATE,7,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(8,'admin01',SYSDATE,'�̰��� ���',8,SYSDATE,8,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(9,'admin01',SYSDATE,'�̰��� ���',9,SYSDATE,9,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(10,'admin01',SYSDATE,'�̰��� ���',1,SYSDATE,10,1,1,1,1,1,1);
INSERT INTO JBOARD_COMMENT VALUES
(11,'admin01',SYSDATE,'�̰��� ���',11,SYSDATE,11,1,1,1,1,1,1);

DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE IQTYPE CASCADE CONSTRAINTS;
DROP TABLE INQUIRY CASCADE CONSTRAINTS;
DROP TABLE ANSWER CASCADE CONSTRAINTS;

--****************************************************************************************************

--��������
CREATE TABLE NOTICE(
    NO_NO NUMBER,
    NO_ID VARCHAR2(20) NOT NULL,
    NO_TITLE VARCHAR2(50) NOT NULL,
    NO_CONTENT VARCHAR2(4000) NOT NULL,
    NO_DATE DATE NOT NULL,
    NO_COUNT NUMBER NOT NULL,
    NO_ORIGINAL VARCHAR2(50),
    NO_RENAME VARCHAR2(50),
    
    CONSTRAINT PK_NNO PRIMARY KEY (NO_NO),
    CONSTRAINT FK_NID FOREIGN KEY (NO_ID) REFERENCES MEMBER ON DELETE SET NULL
);
COMMENT ON COLUMN NOTICE.NO_NO IS '�۹�ȣ';
COMMENT ON COLUMN NOTICE.NO_ID IS '�����ھ��̵�';
COMMENT ON COLUMN NOTICE.NO_TITLE IS '����';
COMMENT ON COLUMN NOTICE.NO_CONTENT IS '����';
COMMENT ON COLUMN NOTICE.NO_DATE IS '�ۼ���¥';
COMMENT ON COLUMN NOTICE.NO_COUNT IS '��ȸ��';
COMMENT ON COLUMN NOTICE.NO_ORIGINAL IS '������������';
COMMENT ON COLUMN NOTICE.NO_RENAME IS '����������';

INSERT INTO NOTICE VALUES(1, 'admin01', '�������� �����Դϴ�.', '���������� ���� �����߽��ϴ�. ���� �̿����ּ���~', '2020/06/30', 5, null, null);
INSERT INTO NOTICE VALUES(2, 'admin01', '��������1', '�߰�ŷ��� �� �������ּ���~', '2020/07/01', 3, null, null);
INSERT INTO NOTICE VALUES(3, 'admin01', '��������2', 'Ŀ�´�Ƽ�� ���� �ø� �� ���� �����Դϴ�~', '2020/07/03', 1, null, null);
INSERT INTO NOTICE VALUES(4, 'admin01', '��������3', '�Ű� ���ϸ� ������Ʈ�� �÷��� �� �ֽ��ϴ�. �������ּ���', '2020/07/03', 6, null, null);
INSERT INTO NOTICE VALUES(5, 'admin01', '��������4', '������Ʈ�� �÷����� �α��� ������ ���� �� �ֽ��ϴ�.', '2020/07/05', 10, null, null);
INSERT INTO NOTICE VALUES(6, 'admin01', '��������5', '���������� ���� �����߽��ϴ�. ���� �̿����ּ���~', '2020/07/07', 5, null, null);
INSERT INTO NOTICE VALUES(7, 'admin01', '��������6', '�߰�ŷ��� �� �������ּ���~', '2020/07/10', 3, null, null);
INSERT INTO NOTICE VALUES(8, 'admin01', '��������7', 'Ŀ�´�Ƽ�� ���� �ø� �� ���� �����Դϴ�~', '2020/07/11', 1, null, null);
INSERT INTO NOTICE VALUES(9, 'admin01', '��������8', '�Ű� ���ϸ� ������Ʈ�� �÷��� �� �ֽ��ϴ�. �������ּ���', '2020/07/13', 6, null, null);
INSERT INTO NOTICE VALUES(10, 'admin01', '��������9', '������Ʈ�� �÷����� �α��� ������ ���� �� �ֽ��ϴ�.', '2020/07/20', 10, null, null);
INSERT INTO NOTICE VALUES(11, 'admin01', '��������10', '���������� ���� �����߽��ϴ�. ���� �̿����ּ���~', '2020/07/25', 5, null, null);
INSERT INTO NOTICE VALUES(12, 'admin01', '��������11', '�߰�ŷ��� �� �������ּ���~', '2020/07/26', 3, null, null);
INSERT INTO NOTICE VALUES(13, 'admin01', '��������12', 'Ŀ�´�Ƽ�� ���� �ø� �� ���� �����Դϴ�~', '2020/07/24', 1, null, null);
INSERT INTO NOTICE VALUES(14, 'admin01', '��������13', '�Ű� ���ϸ� ������Ʈ�� �÷��� �� �ֽ��ϴ�. �������ּ���', '2020/07/27', 6, null, null);
INSERT INTO NOTICE VALUES(15, 'admin01', '��������14', '������Ʈ�� �÷����� �α��� ������ ���� �� �ֽ��ϴ�.', '2020/07/30', 10, null, null);

--���ֹ�������
CREATE TABLE FAQ(
    FAQ_NO NUMBER,
    FAQ_ID VARCHAR2(20) NOT NULL,
    FAQ_TITLE VARCHAR2(50) NOT NULL,
    FAQ_CONTENT VARCHAR2(4000) NOT NULL,
    FAQ_DATE DATE NOT NULL,
    FAQ_COUNT NUMBER NOT NULL,
    FAQ_CATEGORY NUMBER NOT NULL,
    
    CONSTRAINT PK_FNO PRIMARY KEY (FAQ_NO),
    CONSTRAINT FK_FID FOREIGN KEY (FAQ_ID) REFERENCES MEMBER ON DELETE SET NULL
);
COMMENT ON COLUMN FAQ.FAQ_NO IS '�۹�ȣ';
COMMENT ON COLUMN FAQ.FAQ_ID IS '������ ���̵�';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '����';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '����';
COMMENT ON COLUMN FAQ.FAQ_DATE IS '�ۼ���¥';
COMMENT ON COLUMN FAQ.FAQ_COUNT IS '��ȸ��';
COMMENT ON COLUMN FAQ.FAQ_CATEGORY IS 'ȸ��1, �߰�2, Ŀ��3, ����4';

INSERT INTO FAQ VALUES(1, 'admin01', '�߰�ŷ��� � ����ΰ���?', '���ŷ� ����Դϴ�~', '2020/06/30', 5, 2);
INSERT INTO FAQ VALUES(2, 'admin01', '�α����� ��� �ϳ���?', '������ ��� ���� �α��� ��ư�� �����ּ���~', '2020/07/01', 3, 1);
INSERT INTO FAQ VALUES(3, 'admin01', '�α׾ƿ��� ��� �ϳ���?', '������ ��� ���� �α��� ��ư�� �����ּ���~', '2020/07/03', 1, 1);
INSERT INTO FAQ VALUES(4, 'admin01', 'Ż��� ��� �ϳ���?', 'ȸ�������������������� Ż���ϱ� ��ư�� �����ּ���', '2020/07/03', 6, 1);
INSERT INTO FAQ VALUES(5, 'admin01', '�������� ��� �����ϳ���', 'ȸ�������������������� �����ϱ� ��ư�� �����ּ���', '2020/07/05', 10, 1);
INSERT INTO FAQ VALUES(6, 'admin01', '�߰�ŷ�~~', '�����Ҥ��ȿ������ˤ�������Ȩ���Ҥ���������������������', '2020/07/07', 5, 2);
INSERT INTO FAQ VALUES(7, 'admin01', 'Ŀ�´�Ƽ~~', '�������������;�Ӥ��������������ߤ��ˤ����������ڷ�', '2020/07/10', 3, 3);
INSERT INTO FAQ VALUES(8, 'admin01', 'Ŀ�´�Ƽ~~3', '~~~~~~~~���������������������ä�����������������������~~~~~~~~~~~~~~~', '2020/07/11', 1, 3);
INSERT INTO FAQ VALUES(9, 'admin01', '��������', '~~~~~~~~����������������������~~~~~~��������������������������~~~~~~~~~', '2020/07/13', 6, 4);
INSERT INTO FAQ VALUES(10, 'admin01', '��������123', '~~~~~~~~���������ȳ𤾤�����ȿ�~~~~~~~~~~~~~~~', '2020/07/20', 10, 4);
INSERT INTO FAQ VALUES(11, 'admin01', '�߰�ŷ�32~~', '�����Ҥ��ȿ������ˤ�������Ȩ���Ҥ���������������������', '2020/07/23', 5, 2);
INSERT INTO FAQ VALUES(12, 'admin01', 'Ŀ�´�Ƽ235~~', '�������������;�Ӥ��������������ߤ��ˤ����������ڷ�', '2020/07/24', 3, 3);
INSERT INTO FAQ VALUES(13, 'admin01', 'Ŀ�´�Ƽ~~', '~~~~~~~~���������������������ä�����������������������~~~~~~~~~~~~~~~', '2020/07/12', 1, 3);
INSERT INTO FAQ VALUES(14, 'admin01', '��������26', '~~~~~~~~����������������������~~~~~~��������������������������~~~~~~~~~', '2020/07/13', 6, 4);
INSERT INTO FAQ VALUES(15, 'admin01', '��������98', '~~~~~~~~���������ȳ𤾤�����ȿ�~~~~~~~~~~~~~~~', '2020/07/26', 10, 4);

--����
CREATE TABLE IQTYPE(
    IQ_TYPE VARCHAR2(20) CONSTRAINT PK_IQTYPE PRIMARY KEY
);
COMMENT ON COLUMN IQTYPE.IQ_TYPE IS '����';

INSERT INTO IQTYPE VALUES('ȸ������');
INSERT INTO IQTYPE VALUES('�߰�ŷ� �Ű�');
INSERT INTO IQTYPE VALUES('Ŀ�´�Ƽ �Ű�');
INSERT INTO IQTYPE VALUES('����');
INSERT INTO IQTYPE VALUES('�����ϱ�');
INSERT INTO IQTYPE VALUES('��Ÿ');

--���ǰԽñ�
CREATE TABLE INQUIRY(
    IQ_NO NUMBER,
    IQ_ID VARCHAR2(20) CONSTRAINT FK_IQID REFERENCES MEMBER ON DELETE CASCADE,
    IQ_TITLE VARCHAR2(50) NOT NULL,
    IQ_CONTENT VARCHAR2(4000) NOT NULL,
    IQ_DATE DATE DEFAULT SYSDATE NOT NULL,
    IQ_ANSWER CHAR(1) DEFAULT 'N' NOT NULL CHECK (IQ_ANSWER = 'Y' OR IQ_ANSWER = 'N'),
    IQ_ORIGINAL VARCHAR2(50),
    IQ_RENAME VARCHAR2(50),
    IQ_ORIGINAL2 VARCHAR2(50),
    IQ_RENAME2 VARCHAR2(50),
    IQ_ORIGINAL3 VARCHAR2(50),
    IQ_RENAME3 VARCHAR2(50),
    IQ_TYPE VARCHAR2(20) NOT NULL CONSTRAINT FK_IQTYPE REFERENCES IQTYPE,
    CONSTRAINT PK_IQNOID PRIMARY KEY (IQ_NO, IQ_ID)
);
COMMENT ON COLUMN INQUIRY.IQ_NO IS '�۹�ȣ';
COMMENT ON COLUMN INQUIRY.IQ_ID IS 'ȸ�����̵�';
COMMENT ON COLUMN INQUIRY.IQ_TITLE IS '����';
COMMENT ON COLUMN INQUIRY.IQ_CONTENT IS '����';
COMMENT ON COLUMN INQUIRY.IQ_DATE IS '�ۼ���¥';
COMMENT ON COLUMN INQUIRY.IQ_ANSWER IS '�亯����';
COMMENT ON COLUMN INQUIRY.IQ_ORIGINAL IS '�������� ����';
COMMENT ON COLUMN INQUIRY.IQ_RENAME IS '������ ����';
COMMENT ON COLUMN INQUIRY.IQ_ORIGINAL2 IS '�������� ����2';
COMMENT ON COLUMN INQUIRY.IQ_RENAME2 IS '������ ����2';
COMMENT ON COLUMN INQUIRY.IQ_ORIGINAL3 IS '�������� ����3';
COMMENT ON COLUMN INQUIRY.IQ_RENAME3 IS '������ ����3';
COMMENT ON COLUMN INQUIRY.IQ_TYPE IS '����';

-- INSERT�Ϸ��� ���̵������� �ʿ��մϴ�~~~~~
INSERT INTO INQUIRY VALUES(1, 'user01', '�����Ҳ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/01', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(2, 'user04', 'ȸ������', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/02', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(3, 'user02', '�ȳ�~~', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/03', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(4, 'user03', 'Ż���ҷ���~', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/07', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(5, 'user01', 'ȸ������ �����ϰ�;��', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/09', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(6, 'user02', '�����ҷ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/12', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(7, 'user03', '�����ϰ� ������ ��� �ؿ�', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/14', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, 'ȸ������');
INSERT INTO INQUIRY VALUES(8, 'user05', '�����߰��߾��', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/03', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(9, 'user01', '�˻������Դϴ�/', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/07', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(10, 'user02', 'ȸ�������Ϸ��µ� �ȵǳ׿�', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/07', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(11, 'user02', '������ 3���̻�ȵǳ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/16', DEFAULT, NULL, NULL, NULL, NULL, NULL, NULL, '����');
INSERT INTO INQUIRY VALUES(12, 'user03', '�����Ҳ���', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/17', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '�����ϱ�');
INSERT INTO INQUIRY VALUES(13, 'user04', '��Ÿ���ǻ����Դϴ�.', '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/18', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, '��Ÿ');

--�亯�Խñ�
CREATE TABLE ANSWER(
    AN_NO NUMBER NOT NULL CONSTRAINT PK_ANNO PRIMARY KEY,
    AN_CONTENT VARCHAR2(4000) NOT NULL,
    AN_DATE DATE DEFAULT SYSDATE NOT NULL,
    IQ_NO NUMBER NOT NULL,
    IQ_ID VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_IQUNOID FOREIGN KEY (IQ_NO, IQ_ID) REFERENCES INQUIRY ON DELETE CASCADE
);
COMMENT ON COLUMN ANSWER.AN_NO IS '�۹�ȣ';
COMMENT ON COLUMN ANSWER.AN_CONTENT IS '����';
COMMENT ON COLUMN ANSWER.AN_DATE IS '�ۼ���¥';
COMMENT ON COLUMN ANSWER.IQ_NO IS '���۹�ȣ';
COMMENT ON COLUMN ANSWER.IQ_ID IS '�����ۼ���';

-- INSERT�Ϸ��� ���̵������� �ʿ��մϴ�~~~~~
INSERT INTO ANSWER VALUES(1, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/03', '3', 'user02');
INSERT INTO ANSWER VALUES(2, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/07', '4', 'user03');
INSERT INTO ANSWER VALUES(3, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/16', '12', 'user03');
INSERT INTO ANSWER VALUES(4, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/07/01', '13', 'user04');
INSERT INTO ANSWER VALUES(5, '���ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ��ǹ���', '2020/06/16', '10', 'user02');

COMMIT;





