/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-14 01:58:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin.cboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cboard.model.vo.Cboard;
import member.model.vo.Member;
import java.util.ArrayList;
import member.model.vo.Member;

public final class communityAdminWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/admin/cboard/../include/admin_head.jsp", Long.valueOf(1597277304955L));
    _jspx_dependants.put("/views/admin/cboard/../include/admin_footer.jsp", Long.valueOf(1597209052473L));
    _jspx_dependants.put("/views/admin/cboard/../include/admin_header.jsp", Long.valueOf(1597363300523L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("cboard.model.vo.Cboard");
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Cboard> clist = (ArrayList<Cboard>)request.getAttribute("list");
	String local = String.valueOf(request.getAttribute("local"));
	String search = String.valueOf(request.getAttribute("search"));
	String keyword = String.valueOf(request.getAttribute("keyword"));
	String[] localArr = { "강남구", "강동구", "강북구", "강서구", "관악구", "광진구", "구로구", "금천구", "노원구", "도봉구", "동대문구", "동작구", "마포구", 
			"서대문구", "서초구", "성동구", "성북구", "송파구", "양천구", "영등포구", "용산구", "은평구", "종로구", "중구", "중랑구" };

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<meta name=\"title\" content=\"Anavada\" />\r\n");
      out.write("<meta name=\"description\" content=\"Anavada 설명\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Anavada 키워드\" />\r\n");
      out.write("\r\n");
      out.write("<title>Anavada 관리자</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/anavada/resources/admin/css/common.css\">\r\n");
      out.write("<script src=\"/anavada/resources/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/anavada/resources/js/member.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--티스토리 불펌금지-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var omitformtags=[\"input\", \"textarea\", \"select\"]\r\n");
      out.write("    omitformtags=omitformtags.join(\"|\")\r\n");
      out.write("    function disableselect(e){\r\n");
      out.write("    if (omitformtags.indexOf(e.target.tagName.toLowerCase())==-1)\r\n");
      out.write("        return false\r\n");
      out.write("    }\r\n");
      out.write("    function reEnable(){\r\n");
      out.write("        return true\r\n");
      out.write("    }\r\n");
      out.write("    if (typeof document.onselectstart!=\"undefined\")\r\n");
      out.write("        document.onselectstart=new Function (\"return false\")\r\n");
      out.write("    else{\r\n");
      out.write("        document.onmousedown=disableselect\r\n");
      out.write("        document.onmouseup=reEnable\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
 Member loginMember = (Member)session.getAttribute("loginMember"); 
      out.write('\r');
      out.write('\n');
 Member member = (Member)request.getAttribute("member"); 
      out.write('\r');
      out.write('\n');
 ArrayList<Member> list = (ArrayList<Member>)request.getAttribute("list"); 
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body oncontextmenu=\"return false\" onselectstart=\"return false\" ondragstart=\"return false\">\r\n");
      out.write("\t<div id=\"wrap\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("  <header id=\"admin_header\">\r\n");
      out.write("   \r\n");
      out.write("    <h1 class=\"logo\">Anavada</h1>  \r\n");
      out.write("    \r\n");
      out.write("    <!-- gnb -->\r\n");
      out.write("    <div class=\"admin_gnb\">\r\n");
      out.write("        \r\n");
      out.write("        <h2><p>회원관리</p></h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"/anavada/mlist.ad?secessionOK=N\">전체회원</a></li>\r\n");
      out.write("            <li><a href=\"/anavada/mlist.ad?secessionOK=Y\">탈퇴회원</a></li>\r\n");
      out.write("            <li><a href=\"../member/memberDeclare.jsp\">신고회원</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <h2><p>중고거래/커뮤니티관리</p></h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"../product/product_list.jsp\">중고거래</a></li>\r\n");
      out.write("            <li><a href=\"/anavada/adclistview.ad\">커뮤니티</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <h2><p>지역축제</p></h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"../fboard/adminfboardList.jsp\">지역축제</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <h2><p>게시판관리</p></h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"/anavada/anlist.ss\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"/anavada/aflist.ss\">FAQ</a></li>\r\n");
      out.write("            <li><a href=\"/anavada/ailist.ss\">문의하기</a></li>\r\n");
      out.write("            <li><a href=\"/anavada/dlist.ad\">신고자관리</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("        <h2><p>홈페이지관리</p></h2>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"/anavada/blist.ad\">사용자배너</a></li>\r\n");
      out.write("            <li><a href=\"/anavada/mypage.cp?memberId=");
      out.print( loginMember.getMemberId() );
      out.write("\">관리자 정보변경</a></li>\r\n");
      out.write("            <li class=\"homeBtn\"><a href=\"/anavada/\">home</a></li>\r\n");
      out.write("            <li class=\"logoutBtn\"><a href=\"/anavada/logout\">로그아웃</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //gnb -->\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"admin_container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 상단 타이틀 -->\r\n");
      out.write("\t\t\t<div class=\"admin_title\">\r\n");
      out.write("\t\t\t\t<div class=\"admin_path\">\r\n");
      out.write("\t\t\t\t\t<h3>커뮤니티</h3>\r\n");
      out.write("\t\t\t\t\t<h2>| 글작성</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //상단 타이틀 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"write-area\">\r\n");
      out.write("\t\t\t\t<h2>관리자 커뮤니티 작성</h2>\r\n");
      out.write("\t\t\t\t<form action=\"/anavada/adcwrite.ad\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"writer\" value=\"");
      out.print( loginMember.getMemberId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>지역 분류</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"local\" class=\"LocationSelect\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option selected=\"selected\" value=\"\">지역선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">강남구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">강동구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">강북구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">강서구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\">관악구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"6\">광진구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"7\">구로구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"8\">금천구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"9\">노원구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"10\">도봉구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"11\">동대문구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"12\">동작구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"13\">마포구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"14\">서대문구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"15\">서초구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"16\">성동구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"17\">성북구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"18\">송파구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"19\">양천구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"20\">영등포구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"21\">용산구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"22\">은평구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"23\">종로구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"24\">중구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"25\">중랑구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>제목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"title\" class=\"form-control w100p\" placeholder=\"제목\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>내용</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"content\" rows=\"10\" cols=\"1000\" class=\"form-control\" style=\"resize: none; width: 100%; min-height: 300px; max-height: 300px;\" required=\"required\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(int i = 0; i < 4; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t첨부파일");
      out.print(i +1 );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"ofile");
      out.print(i + 1 );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<div class=\"write-btn\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn btn_list\" href=\"/anavada/adclistview.ad?page=1&local=0\" class=\"btn btn-list\">목록</a>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success\">작성하기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<footer id=\"admin_footer\">\r\n");
      out.write("\t<address>Copyright 2020. Anavada. All Rights Reserved</address>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
